"""Repères d'âge des scénarios pour la chronologie adaptée de Nexus Arcana (2033).

Les dates précises qui existaient déjà dans les fiches sont conservées. Les autres
dates contemporaines sont des choix de continuité du forum, pas des dates canoniques.
Pour les personnages antiques, la série ne donne pas de jour/mois fiable : on
indique donc une période estimée au lieu d'inventer une précision historique.
"""

# slug: (âge atteint en 2033 ou âge chronologique/apparent, date de naissance)
SCENARIO_AGES = {
    'abigael-jameson-caine': ('33 ans en 2033', '9 août 2000 · date adaptée à Nexus Arcana'),
    'alaric-saltzman': ('55 ans en 2033', '12 mai 1978 · date adaptée à Nexus Arcana'),
    'allison-argent': ('30 ans en 2033 · âge conservé après son retour', '6 février 2003 · naissance décalée pour la chronologie du forum'),
    'andy-trudeau': ('65 ans depuis sa naissance en 2033 · apparence figée depuis sa mort', '15 mars 1968'),
    'aurora-de-martel': ('Environ 1 057 ans en 2033 · apparence de jeune adulte', 'Vers 976 · jour et mois inconnus'),
    'billie-jenkins': ('34 ans en 2033', '14 septembre 1999 · date adaptée à Nexus Arcana'),
    'bonnie-bennett': ('30 ans en 2033', '5 février 2003 · date adaptée à Nexus Arcana'),
    'briseis-argent': ('31 ans en 2033', '4 juin 2002 · date propre à Nexus Arcana'),
    'camille-oconnell': ('34 ans depuis sa naissance en 2033 · apparence figée depuis sa transformation', '22 avril 1999 · date adaptée à Nexus Arcana'),
    'caroline-forbes-salvatore': ('30 ans depuis sa naissance en 2033 · apparence de jeune adulte depuis sa transformation', '10 octobre 2003 · date adaptée à Nexus Arcana'),
    'chris-argent': ('55 ans en 2033', '8 juillet 1978 · date adaptée à Nexus Arcana'),
    'christopher-halliwell': ('29 ans en 2033', '16 juillet 2004'),
    'christie-jenkins': ('35 ans depuis sa naissance en 2033 · apparence physique plus jeune que Billie depuis son retour', '20 janvier 1998 · date adaptée à Nexus Arcana'),
    'cole-turner': ('148 ans depuis sa naissance en 2033 · apparence d’un homme d’une quarantaine d’années', '14 novembre 1885, San Francisco'),
    'coop-everhart': ('Âge chronologique indéterminé · apparence d’un homme d’une quarantaine d’années', 'Date inconnue · existence antérieure à l’époque contemporaine'),
    'cora-hale': ('28 ans en 2033', '18 septembre 2005 · date adaptée à Nexus Arcana'),
    'damon-salvatore': ('194 ans depuis sa naissance en 2033 · apparence d’environ 25 ans', '18 juin 1839'),
    'davina-claire': ('29 ans en 2033', '12 mai 2004 · date adaptée à Nexus Arcana'),
    'derek-hale': ('36 ans en 2033', '24 décembre 1997 · date adaptée à Nexus Arcana'),
    'dior-montana': ('54 ans en 2033', '18 avril 1979 · date propre à Nexus Arcana'),
    'elena-gilbert-salvatore': ('30 ans depuis sa naissance en 2033 · apparence de jeune adulte depuis sa transformation', '22 juin 2003 · date adaptée à Nexus Arcana'),
    'elijah-mikaelson': ('Environ 1 055 ans depuis sa naissance en 2033 · apparence adulte figée', 'Vers 978 · jour et mois inconnus'),
    'elyse-halliwell': ('26 ans en 2033', '3 décembre 2007'),
    'enzo-st-john': ('Environ 157 ans depuis sa naissance en 2033 · apparence adulte figée', 'Vers 1876 · jour et mois inconnus'),
    'esther-mikaelson': ('Plus d’un millénaire depuis sa naissance · apparence adulte', 'Vers 950 · jour et mois inconnus'),
    'finn-mikaelson': ('Environ 1 059 ans depuis sa naissance en 2033 · apparence adulte figée', 'Vers 974 · jour et mois inconnus'),
    'freya-mikaelson': ('Environ 1 061 ans depuis sa naissance en 2033 · apparence adulte', 'Vers 972 · jour et mois inconnus'),
    'harry-greenwood': ('Environ 105 ans depuis sa naissance en 2033 · apparence d’une quarantaine d’années', 'Vers 1928 · jour et mois inconnus, avant sa transformation'),
    'hayley-marshall': ('43 ans depuis sa naissance en 2033 · apparence figée depuis sa transformation', '6 juin 1990 · date adaptée à Nexus Arcana'),
    'henry-jr-mitchell': ('26 ans en 2033', '2 septembre 2007'),
    'henry-mitchell': ('60 ans en 2033', '12 février 1973, San Francisco'),
    'hope-mikaelson': ('23 ans en 2033', '2 mai 2010 · naissance décalée pour la chronologie du forum'),
    'isaac-lahey': ('29 ans en 2033', '21 août 2004 · date adaptée à Nexus Arcana'),
    'isabella-montana': ('25 ans atteints en 2033', '15 décembre 2008'),
    'jackson-whittemore': ('29 ans en 2033', '30 janvier 2004 · date adaptée à Nexus Arcana'),
    'jensen-turner': ('31 ans en 2033', '14 octobre 2002'),
    'jeremy-gilbert': ('28 ans en 2033 · cadet d’Elena', '13 octobre 2005 · date adaptée à Nexus Arcana'),
    'jordan-parrish': ('35 ans en 2033', '6 novembre 1998 · date adaptée à Nexus Arcana'),
    'josie-saltzman': ('21 ans en 2033 · jumelle de Lizzie', '15 mars 2012 · naissance décalée pour la chronologie du forum'),
    'kai-parker': ('61 ans depuis sa naissance en 2033 · apparence de jeune adulte préservée par le monde-prison', 'Vers 1972 · jour et mois inconnus'),
    'caleb-hawkins': ('23 ans depuis sa naissance en 2033 · apparence de jeune adulte figée', '19 août 2010 · date adaptée à Nexus Arcana'),
    'kate-argent': ('52 ans depuis sa naissance en 2033 · sœur cadette de Chris', '16 octobre 1981 · date adaptée à Nexus Arcana'),
    'katherine-pierce': ('Environ 560 ans depuis sa naissance en 2033 · apparence de jeune adulte', 'Vers 1473 · jour et mois inconnus'),
    'katlyn-mitchell': ('26 ans en 2033 · jumelle de Tamora', '22 juillet 2007'),
    'kaya-montana': ('53 ans en 2033', '11 septembre 1980 · date propre à Nexus Arcana'),
    'kira-yukimura': ('28 ans en 2033', '3 janvier 2005 · date adaptée à Nexus Arcana'),
    'klaus-mikaelson': ('Environ 1 053 ans depuis sa naissance en 2033 · apparence adulte figée', 'Vers 980 · jour et mois inconnus'),
    'kol-mikaelson': ('Environ 1 051 ans depuis sa naissance en 2033 · apparence adulte figée', 'Vers 982 · jour et mois inconnus'),
    'landon-kirby': ('23 ans en 2033', '17 octobre 2010 · date adaptée à Nexus Arcana'),
    'laura-hale': ('39 ans depuis sa naissance en 2033 · apparence à préciser selon son retour', '8 juin 1994 · date adaptée à Nexus Arcana'),
    'leo-wyatt': ('109 ans depuis sa naissance en 2033 · apparence d’une quarantaine d’années', '7 mai 1924, San Francisco'),
    'liam-dunbar': ('25 ans en 2033 · plus jeune que la première meute de Scott', '7 avril 2008 · date adaptée à Nexus Arcana'),
    'lizzie-saltzman': ('21 ans en 2033 · jumelle de Josie', '15 mars 2012 · naissance décalée pour la chronologie du forum'),
    'lucien-castle': ('Environ 1 058 ans depuis sa naissance en 2033 · apparence adulte figée', 'Vers 975 · jour et mois inconnus'),
    'lydia-martin': ('28 ans en 2033', '16 mars 2005 · naissance décalée pour la chronologie du forum'),
    'macy-vaughn': ('32 ans en 2033 · aînée de Mélanie et Maggie', '27 novembre 2001 · date adaptée à Nexus Arcana'),
    'maggie-vera': ('25 ans en 2033 · cadette de Macy et Mélanie', '7 août 2008 · date adaptée à Nexus Arcana'),
    'malia-tate': ('29 ans en 2033', '28 novembre 2004 · chronologie adaptée du forum'),
    'marcel-gerard': ('Environ 223 ans depuis sa naissance en 2033 · apparence adulte figée', 'Vers 1810 · jour et mois inconnus'),
    'matt-donovan': ('30 ans en 2033', '23 mars 2003 · date adaptée à Nexus Arcana'),
    'milton-greasley': ('22 ans depuis sa naissance en 2033 · apparence de jeune adulte figée', '3 juin 2011 · date adaptée à Nexus Arcana'),
    'melanie-vera': ('29 ans en 2033 · cadette de Macy, aînée de Maggie', '4 février 2004 · date adaptée à Nexus Arcana'),
    'melinda-halliwell': ('26 ans en 2033', '9 mars 2007'),
    'nadia-petrova': ('543 ans depuis sa naissance en 2033 · apparence adulte figée', 'Vers 1490 · jour et mois inconnus'),
    'nymea-argent': ('29 ans en 2033', '9 avril 2004 · date propre à Nexus Arcana'),
    'paige-matthews-charmed-one': ('56 ans depuis sa naissance en 2033 · apparence d’environ 43 ans', '2 août 1977'),
    'parker-caine': ('28 ans en 2033 · cadet d’Abigael', '26 mai 2005 · date adaptée à Nexus Arcana'),
    'parker-halliwell': ('24 ans en 2033', '2 mai 2009'),
    'peter-hale': ('59 ans en 2033 · oncle de Laura, Derek et Cora', '11 novembre 1974 · date adaptée à Nexus Arcana'),
    'peyton-halliwell': ('22 ans en 2033', '25 décembre 2011'),
    'phoebe-halliwell-charmed-one': ('58 ans depuis sa naissance en 2033 · apparence d’environ 45 ans', '2 novembre 1975'),
    'piper-halliwell-charmed-one': ('60 ans depuis sa naissance en 2033 · apparence d’environ 47 ans', '7 mars 1973'),
    'prudence-johanna-halliwell': ('26 ans en 2033', '14 novembre 2007'),
    'prue-halliwell-charmed-one': ('63 ans depuis sa naissance en 2033 · apparence d’environ 50 ans', '28 octobre 1970'),
    'rafael-waithe': ('23 ans en 2033', '2 décembre 2010 · date adaptée à Nexus Arcana'),
    'rebekah-mikaelson': ('Environ 1 049 ans depuis sa naissance en 2033 · apparence adulte figée', 'Vers 984 · jour et mois inconnus'),
    'scott-mccall': ('29 ans en 2033', '12 novembre 2004 · naissance décalée pour la chronologie du forum'),
    'stefan-salvatore': ('187 ans depuis sa naissance en 2033 · apparence d’environ 17 ans', '1er novembre 1846'),
    'stiles-stilinski': ('28 ans en 2033', '8 avril 2005 · naissance décalée pour la chronologie du forum'),
    'tamora-mitchell': ('26 ans en 2033 · jumelle de Katlyn', '22 juillet 2007'),
    'tatia-petrova': ('Plus d’un millénaire depuis sa naissance · apparence de jeune adulte après son retour', 'Vers 970 · jour et mois inconnus'),
    'tristan-de-martel': ('Environ 1 059 ans depuis sa naissance en 2033 · frère aîné d’Aurora', 'Vers 974 · jour et mois inconnus'),
    'tyler-lockwood': ('30 ans en 2033', '10 février 2003 · date adaptée à Nexus Arcana'),
    'vincent-griffith': ('42 ans en 2033', '29 juin 1991 · date adaptée à Nexus Arcana'),
    'vivienne-montana': ('27 ans atteints en 2033', '22 juillet 2006'),
    'waverly-jameson': ('31 ans en 2033 · cadette d’Abigael', '1er février 2002 · date propre à Nexus Arcana'),
    'wyatt-matthew-halliwell': ('31 ans en 2033', '27 novembre 2002'),
}
