"""Complete scenario sheets still carrying the Vivienne Montana draft template."""

import json
import re
from html import escape, unescape
from html.parser import HTMLParser
from pathlib import Path

from django.conf import settings
from django.db import transaction
from django.utils import timezone

from apps.forum.models import Topic


PROFILES = {
    "vivienne-montana": dict(nature="Sorcière", camp="Bien", sex="Féminin", age="26 ans en 2033", birth="22 juillet 2006", origin="San Francisco · famille Montana", activity="Activité professionnelle au choix", kind="witch", quote="Je peux porter mon nom sans répéter toutes ses erreurs.", traits="Réfléchie, loyale et protectrice ; parfois trop prudente, perfectionniste et méfiante.", story=["Fille de Richard Montana, Vivienne a grandi avec l'idée que la magie exige de la discipline. Les conflits anciens de sa famille, notamment avec les Callaway, lui ont appris à peser les conséquences d'un geste avant d'agir.", "Sa cousine Isabella, fille de Steve Montana, a reçu une éducation différente. Leur désaccord porte moins sur l'affection que sur la manière de vivre leur héritage : Vivienne cherche des limites, Isabella veut disposer librement de ses dons.", "À San Francisco, Vivienne tente de sortir de cette opposition. Elle peut enquêter sur les fautes de la lignée sans devenir la gardienne de toutes les décisions de sa cousine. Son métier et sa vie sentimentale restent ouverts au joueur."]),
    "isabella-montana": dict(nature="Sorcière", camp="Bien", sex="Féminin", age="24 ans en 2033", birth="15 décembre 2008", origin="San Francisco · famille Montana", activity="Tatoueuse, ou autre activité convenue avec le staff", kind="witch", quote="Comprendre ma magie me permettra de choisir ce que j'en fais.", traits="Curieuse, indépendante et généreuse ; impulsive lorsqu'on veut décider à sa place.", story=["Isabella est la fille de Steve Montana. La méfiance de son père envers la magie a longtemps rendu son héritage plus inquiétant que familier. Elle a dû apprendre à formuler elle-même les questions qu'on évitait devant elle.", "Sa cousine Vivienne connaît d'autres facettes de l'histoire familiale. Leur proximité n'efface pas leur désaccord : Isabella refuse que la prudence devienne une interdiction de vivre ou d'expérimenter.", "Son travail de tatoueuse lui offre une existence hors des conflits de lignées. À San Francisco, elle peut chercher des réponses sur les Montana, réparer un lien familial ou suivre une piste qui n'appartient qu'à elle."]),
    "briseis-argent": dict(nature="Elfe · affinité à préciser", camp="Au choix, y compris pour une elfe noire", sex="Féminin", age="Adulte · âge exact à préciser", birth="À fixer avec le staff", origin="Famille Argent · branche elfique de Nexus Arcana", activity="Activité au choix", kind="elf", quote="Mon nom ouvre des portes ; mes choix diront lesquelles je franchis.", traits="Déterminée, attentive et fière ; parfois secrète et prompte à prendre seule les décisions difficiles.", story=["Briséis appartient à une branche elfique portant le nom Argent. La portée de ce nom et ses liens éventuels avec d'autres Argent se définissent avec les joueurs concernés : aucune parenté avec les chasseurs de Beacon Hills n'est imposée.", "Elle a appris à protéger ce qui lui importe sans considérer la tradition comme une réponse à tout. Sa spécialité elfique, lumineuse, sylvestre ou obscure, reste un choix de personnage et ne décide pas de son camp.", "À San Francisco, Briséis cherche un lieu où bâtir des alliances librement. Un ancien serment, un objet de famille ou une rencontre avec un autre peuple elfique peuvent lancer ses premiers sujets sans fixer leur issue."]),
    "nymea-argent": dict(nature="Elfe · affinité à préciser", camp="Au choix, y compris pour une elfe noire", sex="Féminin", age="Adulte · âge exact à préciser", birth="À fixer avec le staff", origin="Famille Argent · branche elfique de Nexus Arcana", activity="Activité au choix", kind="elf", quote="Une tradition peut me guider sans parler à ma place.", traits="Observatrice, patiente et inventive ; méfiante face aux promesses trop faciles.", story=["Nyméa porte un nom lié à une tradition elfique de Nexus Arcana. Son lien exact avec Briséis et avec les autres Argent reste à convenir ; le scénario ne présume ni sœur, ni cousine, ni héritière désignée.", "Elle s'intéresse aux traces laissées par les anciens pactes, tout en refusant de confondre mémoire et obéissance. Son affinité elfique, notamment une éventuelle magie du sang ou des os, doit être choisie et validée comme capacité précise.", "San Francisco lui permet de confronter les récits reçus à des personnes bien réelles. Une archive perdue ou un sanctuaire oublié peut l'amener vers d'autres personnages, sans révélation obligatoire sur leur passé."]),
    "malia-tate": dict(nature="Coyote-garou", camp="Neutre", sex="Féminin", age="29 ans en 2033 · chronologie adaptée", birth="28 novembre 2004 dans la chronologie du forum", origin="Beacon Hills", activity="Activité actuelle au choix", kind="coyote", quote="Je choisis les personnes qui comptent pour moi, une décision après l'autre.", traits="Franche, courageuse et loyale ; parfois impatiente avec les détours ou les conventions.", story=["Une partie de l'enfance de Malia s'est déroulée sous forme de coyote. Son retour à la vie humaine lui a demandé d'apprendre des codes que les autres tenaient pour évidents.", "Les liens avec la famille Tate, Peter Hale et la meute de Scott participent à son histoire sans lui retirer le droit de définir ses relations actuelles. Elle a traversé des pertes et des révélations qui ont rendu la confiance précieuse.", "Dans la continuité du forum, Malia arrive à San Francisco avec son instinct et son expérience, pas avec une loyauté automatique envers une nouvelle meute. Elle peut y chercher une activité, une famille choisie et ses propres raisons de rester."]),
    "kira-yukimura": dict(nature="Kitsune du tonnerre", camp="Neutre", sex="Féminin", age="Adulte · âge ajusté à la chronologie du forum", birth="Date exacte à préciser", origin="Beacon Hills · famille Yukimura", activity="Activité actuelle au choix", kind="kitsune", quote="Apprendre à maîtriser mon pouvoir ne signifie pas renoncer à qui je suis.", traits="Bienveillante, tenace et curieuse ; peut douter d'elle-même lorsque ses pouvoirs la dépassent.", story=["Kira a découvert progressivement son héritage de kitsune et son lien avec l'électricité. Sa famille lui a transmis des réponses partielles, qu'elle a confrontées aux épreuves de Beacon Hills.", "Son apprentissage auprès des Skinwalkers marque une étape importante, sans lui donner d'emblée une maîtrise parfaite. Ses liens passés avec Scott et sa meute comptent, mais leur présent se décide avec les joueurs concernés.", "À San Francisco, Kira reprend sa place parmi les autres à son rythme. Une manifestation électrique difficile à comprendre ou une histoire liée aux esprits peut ouvrir le jeu sans imposer une crise permanente."]),
    "liam-dunbar": dict(nature="Loup-garou", camp="Neutre", sex="Masculin", age="Adulte · âge ajusté à la chronologie du forum", birth="Date exacte à préciser", origin="Beacon Hills", activity="Activité actuelle au choix", kind="wolf", quote="Je peux ressentir la colère sans la laisser décider pour moi.", traits="Brave, loyal et énergique ; impulsif lorsqu'un proche est menacé.", story=["Scott McCall a transformé Liam pour lui sauver la vie. Le passage à la lycanthropie a amplifié ses émotions et l'a obligé à apprendre une maîtrise qu'aucun rang ne garantit.", "Il a grandi au sein de la meute en trouvant ses propres appuis, notamment auprès de Mason. Leurs liens demeurent importants sans fixer la fréquence de leurs rencontres dans le forum.", "À San Francisco, Liam peut éprouver ce qu'il sait faire sans rester l'élève de quelqu'un. Une nouvelle équipe, un entraînement ou une menace touchant ses proches offrent des départs de jeu ouverts."]),
    "isaac-lahey": dict(nature="Loup-garou", camp="Neutre", sex="Masculin", age="Adulte · âge ajusté à la chronologie du forum", birth="Date exacte à préciser", origin="Beacon Hills", activity="Activité actuelle au choix", kind="wolf", quote="Je n'ai plus à prouver que je mérite une place.", traits="Loyal, observateur et résistant ; peut se replier face au contrôle ou à la violence.", story=["La morsure de Derek Hale a changé la vie d'Isaac alors qu'il cherchait déjà à sortir d'un foyer difficile. Devenir loup-garou lui a donné des ressources, sans effacer ce qu'il avait vécu.", "La meute de Derek, puis l'amitié de Scott et les pertes de Beacon Hills ont marqué sa manière de faire confiance. Son passé avec Allison appartient à leur histoire commune, sans relation actuelle imposée.", "À San Francisco, Isaac peut chercher une stabilité qu'il choisit lui-même. Un ancien compagnon de meute, une enquête ou une occasion de protéger quelqu'un peuvent rouvrir des liens à son rythme."]),
    "jackson-whittemore": dict(nature="Loup-garou marqué par un passé de Kanima", camp="Neutre", sex="Masculin", age="Adulte · âge ajusté à la chronologie du forum", birth="Date exacte à préciser", origin="Beacon Hills", activity="Activité actuelle au choix", kind="kanima", quote="Je ne laisserai plus une transformation raconter toute mon histoire.", traits="Ambitieux, lucide et tenace ; parfois arrogant ou défensif lorsqu'il se sent jugé.", story=["Après la morsure, Jackson est devenu le Kanima avant de trouver une autre forme surnaturelle. Cette expérience a laissé des questions sur l'identité, la maîtrise et le pouvoir qu'autrui prétend exercer sur lui.", "Ses liens avec Lydia et Ethan font partie de son parcours ; leur forme actuelle se construit avec les partenaires concernés. Il ne revient pas à Beacon Hills, ni à San Francisco, pour rejouer indéfiniment son ancien rôle.", "Une nouvelle ville lui permet de choisir un métier et des alliances. Les traces de son passé de Kanima peuvent nourrir une intrigue, sans lui accorder toutes les capacités du Kanima et du loup-garou à la fois."]),
    "chris-argent": dict(nature="Humain · chasseur", camp="Neutre", sex="Masculin", age="Adulte · génération des parents de Beacon Hills", birth="Date exacte à préciser", origin="Famille Argent · Beacon Hills", activity="Chasseur expérimenté · autre activité au choix", kind="hunter", quote="La règle qui compte est celle que l'on accepte d'appliquer à soi-même.", traits="Méthodique, courageux et protecteur ; peut devenir inflexible lorsqu'il craint une nouvelle perte.", story=["Chris a grandi dans une famille de chasseurs et a longtemps porté son code comme une certitude. Beacon Hills lui a appris que la nature d'une créature ne suffit pas à juger ses actes.", "Le retour d'Allison dans la continuité du forum lui offre une possibilité de retrouvailles, pas une raison de décider à sa place. Ses rapports avec Scott, Derek et sa sœur Kate restent traversés par des choix difficiles.", "À San Francisco, son expérience peut aider d'autres chasseurs ou des créatures menacées. Il doit cependant gagner leur confiance par ses actes, et ses armes ne lui donnent aucune autorité sur les personnages des autres joueurs."]),
    "kate-argent": dict(nature="Jaguar-garou", camp="Neutre · actes à définir en jeu", sex="Féminin", age="Adulte · génération des parents de Beacon Hills", birth="Date exacte à préciser", origin="Famille Argent · Beacon Hills", activity="Activité actuelle au choix", kind="jaguar", quote="Je connais le prix des erreurs ; reste à voir ce que j'en ferai.", traits="Audacieuse, rusée et déterminée ; peut manipuler ou confondre revanche et justice.", story=["Kate a été élevée dans la tradition des chasseurs Argent. Ses actes à Beacon Hills ont laissé des blessures durables, notamment dans la famille Hale, qui ne disparaissent pas parce qu'elle change de ville.", "Sa transformation en jaguar-garou la place désormais du côté de ceux qu'elle traquait. Ce renversement ne la rend ni innocente ni automatiquement réconciliée avec Chris ou Allison.", "À San Francisco, Kate peut poursuivre ses propres objectifs, rencontrer des adversaires ou tenter une voie différente. Les conséquences de son passé se jouent avec les personnes concernées, sans pardon ni vengeance imposés."]),
    "jordan-parrish": dict(nature="Chien de l'enfer", camp="Neutre", sex="Masculin", age="Adulte · âge ajusté à la chronologie du forum", birth="Date exacte à préciser", origin="Beacon Hills · parcours antérieur au choix", activity="Adjoint du shérif à Beacon Hills · activité actuelle à préciser", kind="hellhound", quote="Protéger quelqu'un commence par comprendre ce qui le menace.", traits="Calme, serviable et persévérant ; parfois déstabilisé par les impulsions de sa nature surnaturelle.", story=["Jordan a exercé comme adjoint du shérif à Beacon Hills. La découverte du chien de l'enfer en lui a bouleversé son rapport au danger et à son propre corps.", "Il a aidé la meute face à plusieurs menaces, tout en apprenant que les instincts du Hellhound ne remplacent ni l'enquête ni le jugement humain. Ses souvenirs et sa maîtrise peuvent encore comporter des zones d'ombre.", "À San Francisco, Jordan peut chercher une fonction proche de la protection civile ou suivre une piste surnaturelle. Le passage vers cette nouvelle vie et ses relations actuelles restent ouverts au joueur."]),
}


POWERS = {
    "witch": [("Télékinésie", "Déplacer un petit objet visible avec effort ; ni corps d'autrui ni masse importante."), ("Perception magique", "Ressentir une magie proche ou présente sur un objet touché, sans en connaître automatiquement l'origine."), ("Bouclier bref", "Amortir un impact limité ; ne protège ni tout un groupe ni durablement."), ("Sceau d'alerte", "Marquer temporairement une ouverture et percevoir son franchissement à proximité, sans identifier le passant.")],
    "elf": [("Perception du vivant", "Repérer une présence vivante proche dans un environnement calme, sans localisation parfaite."), ("Pas discret", "Atténuer ses propres bruits pendant un court déplacement ; ne rend pas invisible."), ("Lueur elfique", "Produire une faible lumière ou une ombre légère selon l'affinité retenue ; aucun contrôle d'autrui."), ("Sceau de refuge", "Signaler magiquement une intrusion dans un petit espace préparé, sans piéger ni blesser.")],
    "wolf": [("Transformation partielle", "Faire apparaître griffes et crocs pour un temps limité ; la fatigue et les blessures restent possibles."), ("Sens aiguisés", "Suivre une trace récente à courte portée, avec erreurs possibles selon le terrain."), ("Force accrue", "Fournir un effort supérieur à celui d'un humain ; aucune victoire automatique."), ("Guérison accélérée", "Récupérer plus vite d'une blessure ordinaire ; ni régénération instantanée ni résurrection.")],
    "coyote": [("Transformation partielle", "Manifester griffes et traits de coyote brièvement ; le contrôle peut faiblir sous stress."), ("Sens aiguisés", "Distinguer une odeur ou un son proche, sans pistage infaillible."), ("Agilité accrue", "Esquiver ou franchir un obstacle réaliste ; n'annule pas les attaques surprises."), ("Guérison accélérée", "Récupérer plus vite d'une blessure ordinaire ; les blessures graves restent dangereuses.")],
    "kitsune": [("Étincelle du tonnerre", "Produire une faible décharge au contact ou à très courte portée ; ne neutralise pas automatiquement."), ("Perception électrique", "Sentir une source électrique proche, sans en connaître le fonctionnement."), ("Lueur de kitsune", "Manifester brièvement une aura visible, sans illusion parfaite ni invisibilité."), ("Réflexes aiguisés", "Réagir plus vite à un danger perçu, sans anticiper une attaque inconnue.")],
    "kanima": [("Transformation partielle", "Manifester brièvement des traits lupins ; le passé de Kanima ne fournit pas une seconde transformation complète."), ("Sens aiguisés", "Suivre une trace proche et récente avec des erreurs possibles."), ("Guérison accélérée", "Récupérer plus vite d'une blessure ordinaire ; aucune régénération instantanée."), ("Venin résiduel", "Un contact de griffes peut provoquer un engourdissement limité, avec possibilité de résistance et accord du joueur touché.")],
    "hunter": [("Observation", "Repérer des indices matériels visibles sans identifier automatiquement une créature."), ("Tir entraîné", "Utiliser une arme ordinaire avec précision en conditions favorables ; aucune touche garantie."), ("Préparation", "Organiser un itinéraire, du matériel et une voie de repli, sans anticiper toute surprise."), ("Premiers secours", "Stabiliser une blessure accessible avec du matériel ; ne remplace pas un soin médical complet.")],
    "jaguar": [("Transformation partielle", "Manifester griffes et traits félins brièvement, sans forme invulnérable."), ("Agilité féline", "Franchir un obstacle ou esquiver dans une limite réaliste ; pas d'évitement automatique."), ("Sens aiguisés", "Percevoir une trace proche, avec limites dues à la foule et au terrain."), ("Guérison accélérée", "Récupérer plus vite de blessures ordinaires ; les blessures graves restent dangereuses.")],
    "hellhound": [("Flamme infernale", "Produire une flamme limitée à courte portée ; ni incendie incontrôlable ni immunité universelle."), ("Résistance à la chaleur", "Supporter mieux une chaleur brève ; ne protège pas des autres blessures."), ("Perception des seuils", "Ressentir une perturbation surnaturelle proche, sans connaître sa cause exacte."), ("Force accrue", "Fournir un effort supérieur à celui d'un humain sur un temps bref ; aucune victoire garantie.")],
}


def para(text):
    return '<p style="line-height:1.8;margin:.65rem 0;">' + escape(text) + "</p>"


def section(title, body):
    return '<section style="margin:1rem 0;padding:1rem;border:1px solid #574477;border-radius:8px;"><h2 style="font-size:1.1rem;color:#c4b5fd;">' + escape(title) + "</h2>" + body + "</section>"


class CheckHTML(HTMLParser):
    def __init__(self):
        super().__init__()
        self.stack = []

    def handle_starttag(self, tag, attrs):
        if tag not in {"img", "br", "hr", "meta", "input"}:
            self.stack.append(tag)

    def handle_endtag(self, tag):
        previous = self.stack.pop() if self.stack else None
        if previous != tag:
            raise ValueError("Balisage HTML invalide près de " + tag + " après " + repr(previous) + " ; pile " + repr(self.stack[-5:]))


def render(topic, old, data):
    image = re.search(r'<img\b[^>]*src="([^"]+)"', old)
    caption = re.search(r'<p\b[^>]*>([^<]*\b[Ff]t [^<]*)</p>', old, re.I)
    credit = re.search(r'<p class="scenario-credit-line"[^>]*>.*?</p>', old, re.S)
    if not image or not caption or not credit:
        raise ValueError("Portrait ou crédit absent : " + topic.slug)
    fields = [("Âge", data["age"]), ("Naissance", data["birth"]), ("Origines", data["origin"]), ("Sexe", data["sex"]), ("Nature", data["nature"]), ("Camp", data["camp"]), ("Activité", data["activity"]), ("Vie sentimentale", "Au choix du joueur ; les liens présents se définissent avec les partenaires concernés")]
    content = '<div data-completed-scenario="1" style="font-family:Georgia,serif;background:#0d0a1a;color:#e2d9f3;padding:clamp(1rem,4vw,2rem);border-radius:10px;max-width:800px;margin:auto;">'
    content += para("✦ Nexus Arcana · Livre des Ombres ✦")
    content += '<header style="display:flex;flex-wrap:wrap;gap:1.5rem;align-items:center;"><div style="flex:1;min-width:180px;"><h1 style="color:#f5d76e;">' + escape(topic.title) + "</h1>" + para(data["nature"] + " · " + data["camp"]) + para("« " + data["quote"] + " »") + "</div>"
    content += '<figure style="margin:0;"><img src="' + escape(image.group(1), quote=True) + '" alt="' + escape(topic.title, quote=True) + '" style="width:200px;max-width:100%;height:320px;object-fit:cover;border-radius:8px;"><figcaption style="max-width:200px;font-size:.75rem;">' + caption.group(1) + "</figcaption></figure></header>"
    content += section("I. Identité", "<dl>" + "".join('<dt style="color:#a78bfa;margin-top:.6rem;">' + escape(label) + '</dt><dd style="margin:.2rem 0;">' + escape(value) + "</dd>" for label, value in fields) + "</dl>")
    powers = POWERS[data["kind"]]
    content += section("II. Quatre capacités de départ", para("Quatre capacités de départ au total. Pour un humain, il s'agit d'aptitudes ordinaires. Chaque amélioration ou nouvelle capacité suit les règles du forum.") + "".join('<div data-base-power="1"><h3 style="color:#f5d76e;font-size:1rem;">' + escape(name) + "</h3>" + para(description) + "</div>" for name, description in powers) + para("La nature du personnage ne donne pas automatiquement les capacités non retenues. Un effet sur un autre personnage se joue avec son accord et les limites de sa fiche."))
    content += section("III. Âme et caractère", para(data["traits"]) + para("Son passé nourrit ses choix sans déterminer toutes ses réactions. Ses nouvelles alliances, ses conflits et ses projets se développent avec les autres joueurs."))
    content += section("IV. Mémoire des âges · Histoire", "".join(para(line) for line in data["story"]))
    content += section("V. Repères pour le jeu", para("Cette fiche suit la continuité de Nexus Arcana en 2033. Les dates adaptées, l'activité présente et les liens avec des personnages joués se précisent avec le staff et les partenaires concernés. Les pouvoirs proposés constituent un point de départ jouable et ne résument pas toutes les évolutions possibles."))
    content += section("Capacités à la création", para("Quatre capacités maximum au total, actives et passives comprises. Les dons décrits dans l'histoire ou liés à l'espèce ne sont pas automatiquement disponibles. Les évolutions suivent le règlement et la boutique ; un humain conserve des aptitudes humaines."))
    credit_text = unescape(re.sub(r"<[^>]+>", " ", credit.group(0))).split("Capacités à la création", 1)[0].strip()
    if "à renseigner" in credit_text:
        credit_text = "Crédits : auteur de l'avatar non indiqué dans la fiche d'origine."
    content += '<p class="scenario-credit-line" style="font-size:.7rem;font-style:italic;">' + escape(credit_text) + "</p></div>"
    checker = CheckHTML()
    try:
        checker.feed(content)
    except ValueError as exc:
        raise ValueError(topic.slug + " : " + str(exc)) from exc
    if checker.stack or content.count('data-base-power="1"') != 4:
        raise ValueError("Fiche invalide : " + topic.slug)
    return content


with transaction.atomic():
    topics = {topic.slug: topic for topic in Topic.objects.select_for_update().filter(category__slug="scenarios-a-prendre", slug__in=PROFILES)}
    if set(topics) != set(PROFILES):
        raise ValueError("Scénarios introuvables : " + repr(set(PROFILES) - set(topics)))
    posts = {slug: topic.posts.select_for_update().order_by("created_at", "pk").first() for slug, topic in topics.items()}
    for slug, post in posts.items():
        if post is None or "Nom du pouvoir" not in post.content or "data-completed-scenario" in post.content:
            raise ValueError("La fiche a changé ou n'est plus incomplète : " + slug)
    replacements = {slug: render(topics[slug], posts[slug].content, data) for slug, data in PROFILES.items()}
    backup_dir = Path(settings.BASE_DIR) / "data" / "scenario_backups"
    backup_dir.mkdir(parents=True, exist_ok=True)
    backup_path = backup_dir / ("unfinished-scenarios-" + timezone.now().strftime("%Y%m%dT%H%M%S%f") + ".json")
    backup_path.write_text(json.dumps([{"topic_id": topics[slug].pk, "post_id": posts[slug].pk, "title": topics[slug].title, "content": posts[slug].content, "cards": topics[slug].scenario_link_cards} for slug in PROFILES], ensure_ascii=False), encoding="utf-8")
    for slug, content in replacements.items():
        post = posts[slug]
        post.content = content
        post.save(update_fields=["content", "is_edited", "updated_at"])
        print(topics[slug].title + " : fiche complétée")
