"""Install the Nexus Arcana race directory, preserving the topic URL."""
import json
from html import escape
from pathlib import Path
from django.conf import settings
from django.db import transaction
from django.utils import timezone
from apps.forum.models import Topic

# These branches are forum proposals, not claims about television canon.
GROUPS = [
('Peuples féeriques et esprits de la nature', [
('Fées', 'Peuple magique lié aux lieux vivants, aux enchantements et aux perceptions.', [
('Fées sylvestres', 'Affinité avec la végétation et les refuges forestiers ; perception des plantes ou camouflage végétal à choisir.'),
('Fées des eaux', 'Affinité avec les sources et les brumes ; respiration aquatique ou manipulation limitée de l’eau à choisir.'),
('Fées lumineuses', 'Lumières féeriques et illusions visuelles. Certaines peuvent être guérisseuses : la guérison doit alors figurer parmi les capacités choisies et validées dans leur fiche. Leur éclat ne détermine pas leur camp.'),
('Fées noires', 'Branche liée à la nuit, aux ombres et aux enchantements trompeurs. Certaines fées noires peuvent aussi entretenir un lien magique avec le sang ou les os, par exemple dans leurs perceptions ou leurs rituels. Un voile d’ombre, une illusion ou la perception des maléfices peuvent également orienter leurs dons. Ces affinités ne déterminent pas leur camp et chaque capacité utilisée doit figurer dans la fiche validée.')], 'Les illusions ne deviennent pas réelles. Le vol, l’invisibilité et le changement de taille ne sont pas offerts automatiquement ; chaque effet retenu appartient aux quatre pouvoirs. Les protections adaptées peuvent dissiper les enchantements.'),
('Elfes', 'Peuple attaché à une mémoire ancienne, à des territoires ou à des traditions magiques.', [
('Elfes sylvains', 'Forêts, pistage et perception du vivant ; leur discrétion repose aussi sur l’apprentissage.'),
('Elfes des sources', 'Rivières, sanctuaires et magie de l’eau ; adaptation originale du forum.'),
('Elfes des astres', 'Lumière et lecture symbolique des cycles ; les présages restent fragmentaires.'),
('Elfes noirs', 'Branche des lieux souterrains, du crépuscule ou des sanctuaires oubliés. Certains peuvent entretenir un lien magique avec le sang ou les os, notamment dans leurs perceptions ou leurs rituels. Vision nocturne, perception des ombres ou enchantement de dissimulation peuvent aussi former leur spécialité. « Noir » désigne une affinité magique, sans imposer apparence, société ou camp ; les capacités choisies doivent figurer dans la fiche validée.')], 'Longévité ne signifie pas invulnérabilité. Ni prescience parfaite ni maîtrise de toutes les magies. Les dons choisis demandent concentration et restent sensibles aux contre-mesures.'),
('Nymphes et satyres', 'Esprits incarnés dont l’identité se construit autour d’un milieu naturel.', [('Nymphes des bois', 'Lien avec un bosquet ou une forêt.'), ('Nymphes des sources', 'Lien avec une source ou une rivière.'), ('Nymphes des roches', 'Lien avec une falaise ou un massif ; branche proposée pour le forum.'), ('Satyres', 'Affinité avec les espaces sauvages et les rythmes du vivant ; branche distincte, pas un cumul de dons de nymphe.')], 'Un lieu d’attache ne devient pas un territoire contrôlé sans limite. Sa dégradation peut affaiblir le personnage ; le lien et ses conséquences se définissent dans la fiche.'),
]),
('Sorciers et héritages magiques', [
('Sorciers Charmed', 'Magie personnelle, sorts et potions dans la continuité Charmed du forum. Les sorciers Charmed ne choisissent aucune branche : chacun définit son camp séparément, selon ses convictions et ses actes.', [], 'Les pouvoirs précis sont choisis dans la fiche validée. Une lignée familiale ou un apprentissage ne constitue pas une sous-race et ne donne aucun don automatique. Un rituel ne permet pas de contourner les quatre pouvoirs de base validés ou de reproduire librement ceux d’un autre personnage.'),
('Sorciers TVD, The Originals et Legacies', 'Le choix de branche décrit l’appartenance à un coven ou une pratique indépendante. Les traditions magiques et les aptitudes se précisent séparément dans la fiche.', [('Sorciers de coven', 'Membres d’un coven choisi et nommé dans la fiche ; leurs pratiques et leurs liens dépendent de ce coven.'), ('Sorciers indépendants', 'Sorciers qui pratiquent hors d’un coven, seuls ou avec des alliés, sans appartenance à une communauté magique établie.')], 'La magie ancestrale est une tradition et le siphonnage une aptitude, pas des branches liées à l’appartenance. Un siphonneur peut appartenir à un coven ou être indépendant : cette aptitude doit figurer dans ses dons validés. Une source n’est pas inépuisable ; aucun de ces choix ne donne accès automatiquement à toutes les traditions ni ne permet de vider la magie d’un autre joueur sans résolution commune.'),
('Hérétiques', 'Héritage de vampire et de siphonneur, à distinguer d’un sorcier ordinaire devenu vampire.', [('Hérétiques de coven', 'Identité construite autour d’une communauté magique.'), ('Hérétiques indépendants', 'Pratique individuelle et recherche d’autonomie ; ce mode de vie n’ajoute aucune capacité.')], 'Quatre pouvoirs au total pour les deux héritages. La magie siphonnée possède une réserve limitée ; faim, contraintes vampiriques et protections restent pertinentes.'),
]),
('Protecteurs, messagers et esprits', [
('Êtres de lumière', 'Protecteurs liés aux déplacements et au soin selon les dons validés. Les Êtres des ténèbres sont décrits dans la famille des natures démoniaques.', [], 'Soin, orbing et immortalité ne sont pas acquis automatiquement. Les missions et les capacités dépendent de la fiche validée.'),
('Cupidons', 'Personnages sensibles aux liens affectifs et aux rencontres.', [('Cupidons des rencontres', 'Affinité avec les rapprochements et les occasions de rencontre.'), ('Cupidons des liens éprouvés', 'Branche originale tournée vers la perception des liens fragilisés.')], 'Aucun amour forcé, rupture automatique ou contrôle des sentiments d’autrui. Le libre choix des partenaires prime.'),
('Valkyries', 'Guerrières liées aux combattants, aux serments et à la mémoire des morts. Leur branche décrit la manière dont elles accomplissent leur mission, sans imposer leur camp ni déterminer leurs pouvoirs.', [('Valkyries gardiennes', 'Veillent sur un lieu, un passage ou une communauté qu’elles se sont engagées à protéger. Leur serment les pousse à défendre ceux qui y trouvent refuge et à préserver la mémoire des combattants tombés. Le lieu protégé et les obligations du serment sont précisés dans la fiche.'), ('Valkyries errantes', 'Parcourent les territoires à la recherche de personnes, de traces de batailles ou de serments oubliés. Elles peuvent escorter des vivants en danger et témoigner du sort des morts, sans être liées durablement à un sanctuaire. Leur quête et les liens qu’elles entretiennent sont précisés dans la fiche ; cette branche est une adaptation du forum.')], 'Ces branches sont des missions, sans don exclusif ni pouvoir supplémentaire. Les capacités choisies figurent dans la fiche validée. Une Valkyrie ne peut ni ressusciter quelqu’un ni s’approprier ou diriger l’âme d’un autre personnage du seul fait de sa mission. Son entraînement ne la rend pas invincible.'),
('Muses', 'Esprits liés à la création et à l’inspiration.', [('Muses des arts', 'Expression visuelle, musique ou écriture.'), ('Muses des idées', 'Branche originale liée à l’invention et à la réflexion.')], 'L’inspiration ne contrôle pas une personne et ne garantit pas sa réussite. Elle ne retire pas ses connaissances ou son talent.'),
('Banshees', 'Dans Teen Wolf, les Banshees, comme Lydia Martin, perçoivent des signes liés à la mort et peuvent manifester un cri surnaturel. Les deux profils ci-dessous décrivent la manière dont un personnage vit et développe ces manifestations : ce ne sont pas des sous-races.', [('Banshees de présage', 'Leur récit met l’accent sur les indices de mort : impressions soudaines, sons, images ou lieux qui prennent sens peu à peu. Elles cherchent à comprendre qui est en danger et ce qui pourrait arriver, sans recevoir de réponse complète ni de date certaine.'), ('Banshees de lamentation', 'Leur récit met l’accent sur le cri : manifestation d’abord involontaire face à un danger ou à un présage, puis éventuellement mieux maîtrisée. Un usage sonore capable de repousser ou de blesser doit être choisi comme capacité et délimité dans la fiche. Ce nom de profil est une adaptation du forum.')], 'Les deux profils peuvent connaître présages et cris selon les pouvoirs validés ; aucun don n’est exclusif à une branche. Une Banshee annonce ou ressent la mort sans la provoquer par nature, sans contrôler les âmes et sans connaître automatiquement l’avenir exact. Les indices restent interprétables, une mort annoncée peut être évitée selon l’intrigue, et un cri offensif conserve une portée et une intensité limitées avec une possibilité de réponse pour les autres joueurs.'),
('Sphinx', 'Créatures associées aux énigmes, aux savoirs et aux présages. Leur branche décrit la façon dont elles abordent la connaissance ; elle ne détermine pas à elle seule leurs pouvoirs.', [('Sphinx des archives', 'Attachés à un lieu, une collection ou une tradition dont ils préservent les récits. Leurs énigmes partent de traces du passé, de témoignages ou de documents. Ils peuvent rechercher une vérité oubliée, mais ne connaissent que ce qu’ils ont appris ou découvert.'), ('Sphinx des carrefours', 'Attentifs aux décisions et aux chemins qui s’ouvrent devant les personnages. Leurs énigmes mettent en lumière des conséquences possibles ou des choix négligés, sans révéler un avenir certain ni décider à la place des autres. Cette branche est une création du forum.')], 'Ces deux branches sont des orientations narratives, sans don exclusif ni pouvoir supplémentaire. Les capacités choisies figurent dans la fiche validée. Aucune omniscience : une archive peut être incomplète ou trompeuse, et un présage reste incertain. Toute prédiction importante dépend de l’intrigue et du maître du jeu ; une énigme ne donne pas de pouvoir absolu sur autrui.'),
]),
('Natures démoniaques et revenantes', [
('Êtres des ténèbres', 'Démons orientés vers la traque ou des manifestations obscures. Ils appartiennent à la nature démoniaque, sans constituer une sous-race imposée aux autres démons.', [], 'Le poison, les déplacements et l’immortalité ne sont pas acquis automatiquement. Un Être des ténèbres peut suivre le Mal ou rester neutre, mais pas rejoindre le camp du Bien. Ses capacités dépendent de la fiche validée.'),
('Démons', 'Les démons de Charmed sont une nature unique aux manifestations variées, qui comprend notamment les Êtres des ténèbres. Feu, perception, métamorphose ou d’autres capacités peuvent être proposés selon l’histoire du personnage : ce sont des pouvoirs possibles, pas des sous-races à choisir.', [], 'Niveau inférieur et niveau supérieur désignent des rangs dans l’Inframonde, sans ajouter de capacités automatiques. La Triade et la Source sont des positions ou des alliances distinctes. Un sorcier maléfique n’est pas un démon du seul fait de son camp ; les Êtres des ténèbres, eux, sont des démons. Un démon peut suivre le Mal ou rester neutre, mais pas rejoindre le camp du Bien. Ses capacités précises doivent figurer dans sa fiche validée.'),
('Vampires', 'Nature vampirique dont les règles dépendent de la continuité retenue. Les profils ci-dessous situent surtout l’ancienneté et l’origine du personnage.', [('Vampires de lignée', 'Vampires ordinaires issus d’une lignée connue. Ils peuvent être jeunes ou plus expérimentés ; cette appellation n’ajoute aucun pouvoir particulier.'), ('Vampires anciens', 'Vampires ayant traversé plusieurs générations, mais toujours moins âgés que les Originels. Leur ancienneté ne donne pas automatiquement leurs capacités.'), ('Vampires originels', 'Réservés aux personnages originels présents dans les séries et aux scénarios déjà existants sur le forum. Aucun Originel inédit ne peut être créé librement.')], 'Une bague de jour est un bijou au lapis-lazuli enchanté par une sorcière pour un vampire précis : elle lui permet de se déplacer au soleil tant qu’il la porte. Elle n’est pas accordée automatiquement à tous les vampires ; sa possession doit figurer dans la fiche validée ou être obtenue en jeu. Perdue, retirée ou privée de son enchantement, elle ne protège plus du soleil. Elle n’annule ni la faim ni les autres vulnérabilités. Les hybrides capables de vivre au soleil n’en ont pas besoin. Un vampire ancien ne peut pas avoir l’âge d’un Originel. Les Originels jouables restent limités aux personnages de la série et aux scénarios existants. La contrainte mentale ne s’impose jamais librement à un joueur.'),
('Phénix', 'Deux origines distinctes portent ce nom dans le crossover. Choisissez la continuité Legacies ou Charmed dans la fiche : elles ne désignent pas la même nature et leurs capacités ne se cumulent pas.', [('Phénix de Legacies', 'Nature surnaturelle illustrée par Landon Kirby. Son histoire est liée à un cycle de mort et de renaissance ; toute renaissance jouable doit être définie dans la fiche avec ses conditions et ses conséquences. Cette origine ne fait pas du personnage une sorcière Phénix de Charmed.'), ('Phénix de Charmed', 'Lignée de sorcières dont Bianca est un exemple. Leur tradition est liée à la magie et à des missions d’assassinat ; la reconstitution du corps montrée dans cette continuité n’est pas la renaissance du Phénix de Legacies. Une sorcière de cette lignée reste une sorcière, pas une créature de feu par défaut.')], 'Le feu, les boules d’énergie, la reconstitution et la renaissance sont des capacités distinctes : aucune n’est accordée automatiquement par le nom ou la branche. Les pouvoirs retenus doivent figurer dans la fiche validée. Une renaissance ou une reconstitution ne permet ni d’annuler librement une mort en RP ni de ressusciter autrui ; le vol de pouvoirs et les effets sur un autre personnage exigent une validation et une résolution commune.'),
]),
('Changeformes et esprits animaux', [
('Loups-garous', 'Nature lupine dont la transformation et les faiblesses suivent l’origine choisie.', [('Lignées TVD / The Originals', 'Héritage et transformation définis selon cette continuité.'), ('Lignées Teen Wolf', 'Origine et fonctionnement définis selon cette continuité.'), ('Alpha, bêta et oméga', 'Statuts de meute, lorsque pertinents ; ce ne sont pas trois races cumulables.')], 'Les contraintes lunaires et vulnérabilités sont validées selon l’origine, sans mélange opportuniste. Un statut alpha ne donne pas un contrôle absolu sur une meute de joueurs.'),
('Autres changeformes', 'Natures animales distinctes : choisir une forme principale.', [('Werecoyotes', 'Affinité coyote et instinct de survie.'), ('Werejaguars', 'Affinité jaguar et approche féline.'), ('Werelions', 'Affinité lion ; modalités adaptées au forum.')], 'Une forme n’accorde pas toutes les capacités des autres changeformes. Sens, force, transformation et régénération éventuelle se répartissent dans la fiche.'),
('Kanimas', 'Nature reptilienne dont l’origine et le rapport à la transformation doivent être expliqués.', [('Kanimas en quête d’identité', 'Transformation et identité au centre du personnage.'), ('Kanimas stabilisés', 'Version adaptée au forum avec une maîtrise partielle validée.')], 'Le venin n’entraîne pas une paralysie automatique sans réponse possible. Aucun lien de maître n’est imposé à un autre personnage.'),
('Chiens de l’enfer (Hellhounds)', 'Dans Teen Wolf, le Hellhound est un esprit surnaturel lié à un hôte humain, comme Jordan Parrish. Il est associé au feu, à la mort et à la protection du monde surnaturel. Malgré son nom français, ce n’est pas un démon de Charmed ni un chien ordinaire vivant dans les enfers. La relation entre l’hôte et l’esprit doit être précisée dans la fiche.', [('Gardiens du surnaturel', 'Profil centré sur la protection d’un lieu, d’un secret ou d’un passage lié au monde surnaturel. La mission et ses limites sont définies dans la fiche ; elle ne confère aucune autorité générale sur les autres créatures.'), ('Veilleurs des morts', 'Profil tourné vers les signes de mort et les événements qui menacent l’équilibre surnaturel. Le personnage peut enquêter ou intervenir selon son histoire, sans prédire chaque décès ni disposer des âmes. Ce profil est une adaptation du forum.')], 'Ces profils décrivent une mission, pas deux sous-races ni des pouvoirs exclusifs. Une manifestation de feu, une transformation, une résistance à la chaleur ou une perception de la mort doit figurer parmi les capacités validées ; aucune immunité totale ni traque infaillible. Le Hellhound ne contrôle pas automatiquement son hôte ou les choix des autres personnages.'),
('Kitsunes', 'Esprits-renards répartis dans Nexus Arcana selon leur affinité dominante. Les douze branches ci-dessous sont la classification jouable du forum, inspirée de Teen Wolf et adaptée à son crossover.', [
('Kitsunes de l’eau', 'Affinité avec les courants et les sources ; une manipulation de l’eau doit être choisie et délimitée dans la fiche.'),
('Kitsunes de la glace', 'Affinité avec le froid, le givre et la glace ; elle ne donne pas automatiquement tous les pouvoirs de l’eau.'),
('Kitsunes du feu', 'Affinité avec les flammes et la chaleur ; portée et intensité dépendent des capacités validées.'),
('Kitsunes de la terre', 'Affinité avec les sols et la pierre ; les manifestations importantes demandent une progression en jeu.'),
('Kitsunes de l’air', 'Affinité avec les vents et les mouvements de l’air ; le vol ou les tempêtes ne sont pas acquis par défaut.'),
('Kitsunes soniques', 'Affinité avec les sons et les vibrations ; portée et effets sur autrui restent limités.'),
('Kitsunes de la lumière', 'Affinité avec la clarté et les phénomènes lumineux ; leur nature ne détermine pas leur camp.'),
('Kitsunes de l’ombre', 'Affinité avec l’obscurité et la dissimulation ; elle ne fait pas automatiquement d’eux des Nogitsune.'),
('Kitsunes des plantes', 'Affinité avec la végétation ; leurs dons nécessitent un environnement et une portée définis.'),
('Kitsunes de l’esprit', 'Affinité avec les perceptions et les manifestations spirituelles ; aucune lecture totale des pensées ou contrôle d’autrui.'),
('Kitsunes du sang', 'Affinité rituelle ou sensorielle liée au sang ; elle ne permet ni contrôle du corps d’autrui ni vol de pouvoirs.'),
('Kitsunes du tonnerre', 'Affinité avec l’électricité et les éclairs ; intensité et précision sont définies dans la fiche.'),
], 'Chaque Kitsune choisit une affinité dominante. La branche oriente ses propositions de pouvoirs sans tous les accorder : quatre capacités maximum à la création, puis progression selon les règles du forum. Les queues et l’âge n’ajoutent aucun don automatique. Les branches sont des adaptations de Nexus Arcana et ne sont pas présentées comme une liste canonique de Teen Wolf.'),
('Chimères', 'Nature composite dont les origines sont fixées avant le jeu.', [('Chimères composites', 'Une seule branche pour toutes les chimères, quelle que soit la combinaison de leurs traits. Les origines et les capacités propres au personnage sont détaillées dans sa fiche.')], 'La combinaison demande validation ; quatre pouvoirs au total, avec des limites communes. Aucun ajout ultérieur de race pour justifier une capacité improvisée.'),
]),
('Sirènes marines et psychiques', [
('Sirènes et tritons marins', 'Peuples aquatiques, distincts des sirènes psychiques.', [('Peuples des mers', 'Milieu marin et grandes étendues d’eau.'), ('Peuples des eaux douces', 'Branche originale liée aux lacs et rivières.'), ('Peuples des abysses', 'Branche originale liée aux profondeurs ; l’obscurité ne détermine pas leur camp.')], 'Respiration aquatique, forme marine et chant éventuel sont précisés dans la fiche. Ni contrôle de l’océan ni séduction irrésistible. La vie à terre possède des conditions définies.'),
('Sirènes psychiques de The Vampire Diaries', 'Êtres psychiques dont les capacités touchent à l’appel, à la perception et à l’influence mentale. Leur origine et leurs capacités sont précisées dans la fiche. Ces sirènes sont distinctes des peuples marins : elles ne possèdent pas de forme aquatique du seul fait de leur nom.', [('Sirènes de l’appel', 'Profil centré sur la voix ou l’appel psychique pour attirer l’attention, établir un lien et influencer une cible à portée définie. La forme de l’appel et ses effets précis doivent être validés : il ne commande pas librement les actes d’un autre personnage.'), ('Sirènes du souvenir', 'Profil centré sur la perception des souvenirs et des failles émotionnelles, à partir d’un lien psychique établi. Une altération de souvenir éventuelle est une capacité distincte, soumise à validation et à l’accord du joueur concerné ; ce profil est une adaptation du forum.')], 'L’appel et le rapport aux souvenirs sont des orientations de jeu, pas des sous-races ni des dons exclusifs. Aucun accès aux âmes, contrôle mental absolu, immortalité ou changement de mémoire n’est acquis par le seul choix de la nature. Les effets sur un autre personnage se résolvent avec son joueur. Aucune queue de poisson, respiration aquatique ou maîtrise de l’eau automatique.'),
]),
('Humains et héritages multiples', [
('Humains', 'Nature humaine ; une profession ou une croyance ne crée pas une sous-race biologique.', [('Humains non initiés', 'Découverte progressive du surnaturel.'), ('Humains initiés', 'Connaissances et liens avec les communautés magiques.'), ('Chasseurs', 'Profil entraîné, avec équipement et compétences justifiés.'), ('Médiums', 'Profil doté de perceptions seulement si celles-ci sont validées.')], 'Un humain sans magie conserve sa nature. Le cadre des quatre capacités de départ se définit avec le staff sans lui attribuer arbitrairement quatre dons surnaturels ; entraînement et équipement ne donnent pas une invulnérabilité.'),
('Hybrides', 'Double héritage explicitement nommé dans la fiche.', [('Sorcier / être de lumière', 'Deux héritages, une seule réserve de quatre pouvoirs.'), ('Sorcier / démon', 'Affinités choisies entre les deux origines.'), ('Vampire / loup-garou', 'Transformation et contraintes communes à définir.'), ('Autres doubles héritages', 'Par exemple fée / sorcier : proposition à justifier et valider, sans disponibilité automatique.')], 'Aucun cumul de deux fiches complètes. Les quatre pouvoirs sont répartis entre les héritages ; les faiblesses ne disparaissent pas simplement parce que le personnage est hybride.'),
('Trybrides', 'Triple héritage exceptionnel de sorcier, vampire et loup-garou. L’éveil éventuel des héritages relève de l’évolution du personnage, pas d’une branche ou d’une sous-race.', [], 'Quatre pouvoirs au total à la création, répartis entre les héritages validés ; aucun triple quota ni éveil libre en cours de sujet. Les capacités nouvellement éveillées suivent les règles de progression et la validation du staff.'),
]),
]


def p(text):
    return '<p style="line-height:1.8;margin:.65rem 0;">' + escape(text) + '</p>'


def render():
    count = sum(len(rows) for _, rows in GROUPS)
    out = '<div data-nexus-race-directory="1" style="font-family:Georgia,serif;background:#0d0a1a;color:#e2d9f3;padding:clamp(1rem,4vw,2rem);border:1px solid #574477;border-radius:10px;max-width:900px;margin:auto;">'
    out += '<h1 style="color:#f5d76e;">Bottin des créatures et des profils</h1>'
    out += p(f'Nexus Arcana · {count} fiches de races et familles. Choisissez une famille dans le sommaire, puis ouvrez la fiche qui vous intéresse.')
    out += '<nav aria-label="Familles de créatures" style="display:flex;flex-wrap:wrap;gap:.65rem;">'
    for i, (group, _) in enumerate(GROUPS):
        out += f'<a href="#race-family-{i}" style="color:#e4d4ff;border:1px solid #745694;border-radius:6px;padding:.55rem;">{escape(group)}</a>'
    out += '</nav><section style="margin:1.3rem 0;padding:1rem;background:#221631;border-radius:8px;"><h2 style="color:#c4b5fd;">Choisir sa nature, sa branche et son camp</h2>'
    out += p('Race ou nature : ce que votre personnage est. Branche ou profil : son affinité, sa tradition ou son statut lorsqu’un tel choix existe. Camp : ses convictions et ses actes. Ces choix sont distincts. Une fée noire ou un elfe noir peut suivre le Bien, le Mal ou la neutralité ; une nature lumineuse ne garantit pas la bonté. En revanche, les démons, y compris les Êtres des ténèbres, ne peuvent pas rejoindre le camp du Bien : ils peuvent suivre le Mal ou rester neutres.')
    out += p('Exemple de fiche : Race — Fée ; Sous-race — Fée noire ; Camp — Bien. Autre exemple : Race — Elfe ; Sous-race — Elfe noir ; Camp — Neutre. Indiquez la branche dans le champ Race de votre profil si aucun champ séparé n’est proposé.')
    out += p('Ce bottin présente la continuité de Nexus Arcana. Les branches descriptives sont des adaptations de jeu du forum, pas une classification officielle commune aux séries. Une tradition, un métier ou un statut est signalé comme tel : ce n’est pas toujours une sous-race biologique.')
    out += p('Les affinités suggèrent des choix : elles ne donnent pas tous les dons cités. Un personnage doté de pouvoirs commence avec quatre pouvoirs de base validés, répartis entre ses éventuels héritages. Un humain sans magie n’obtient pas de pouvoirs surnaturels : ses capacités de départ se définissent selon sa fiche et avec le staff. Une branche ou un profil n’ajoute aucun emplacement. Les améliorations restent régies par le règlement et la boutique.')
    out += '</section>'
    for i, (group, rows) in enumerate(GROUPS):
        out += f'<section id="race-family-{i}" style="scroll-margin-top:100px;margin:1.7rem 0;"><h2 style="color:#f5d76e;">{escape(group)}</h2>'
        for name, description, variants, limits in rows:
            label = escape(name) + (f' · {len(variants)} branches ou profils' if variants else '')
            out += '<details style="border:1px solid #574477;border-radius:8px;margin:.75rem 0;background:#171023;"><summary style="padding:1rem;cursor:pointer;color:#d8c6f4;font-weight:bold;">' + label + '</summary><div style="padding:0 1rem 1rem;">'
            out += p(description)
            if variants:
                out += '<h3 style="font-size:1rem;color:#c4b5fd;">Sous-races, branches ou profils</h3><dl>'
                for branch, text in variants:
                    out += '<dt style="font-weight:bold;color:#e4d4ff;margin-top:1rem;">' + escape(branch) + '</dt><dd style="margin:.3rem 0 0;line-height:1.8;">' + escape(text) + '</dd>'
                out += '</dl>'
            out += '<h3 style="font-size:1rem;color:#c4b5fd;">Limites et repères de jeu</h3>' + p(limits) + '</div></details>'
        out += '</section>'
    out += '<section style="padding:1rem;border:1px solid #745694;border-radius:8px;"><h2 style="color:#c4b5fd;">Proposer une branche ou un profil</h2>'
    out += p('Transmettez au staff : la nature concernée, le nom de la branche ou du profil, son origine dans Nexus Arcana, ses particularités, les capacités de départ proposées s’il y en a, leurs limites et les liens avec les peuples existants. Précisez votre camp séparément. Une nouvelle proposition se valide avant son utilisation en RP.')
    return out + '</section></div>'


with transaction.atomic():
    topic = Topic.objects.select_for_update().get(slug='encyclopedie-des-creatures-et-races')
    post = topic.posts.select_for_update().order_by('created_at', 'pk').first()
    assert post is not None
    content = render()
    assert content.count('<details ') == sum(len(rows) for _, rows in GROUPS)
    assert 'Fées noires' in content and 'Elfes noirs' in content
    folder = Path(settings.BASE_DIR) / 'data/scenario_backups'
    folder.mkdir(parents=True, exist_ok=True)
    (folder / ('race-directory-' + timezone.now().strftime('%Y%m%dT%H%M%S%f') + '.json')).write_text(json.dumps(dict(topic_id=topic.pk, title=topic.title, post_id=post.pk, content=post.content), ensure_ascii=False), encoding='utf-8')
    post.content = content
    post.save(update_fields=['content', 'is_edited', 'updated_at'])
    topic.title = 'Bottin des créatures et des profils'
    topic.save(update_fields=['title'])
    post.refresh_from_db()
    assert post.content == content
    print(f'Bottin enregistré : {sum(len(rows) for _, rows in GROUPS)} fiches, {sum(len(row[2]) for _, rows in GROUPS for row in rows)} branches et profils, {len(GROUPS)} familles.')
