import ast
from pathlib import Path
source=Path('fill_mikaelson_scenarios.py').read_text(encoding='utf-8-sig')
source=source.replace('mikaelson_data.json','marcel_data.json').replace('assert len(topics)==8','assert len(topics)==1').replace("'mikaelson-'","'marcel-'").replace('data-mikaelson-scenario','data-marcel-scenario')
start=source.index('def abilities(d):');end=source.index('with transaction.atomic():',start)
source=source[:start]+'''def abilities(d):
 parts=[('Force surnaturelle','Force supérieure à celle d’un humain sur une action ciblée. Ce don n’accorde ni vitesse accrue ni invulnérabilité et ne garantit aucune victoire.'),('Vitesse surnaturelle','Accélération sur une courte distance dégagée. Les obstacles restent présents ; aucune téléportation ni perception surnaturelle ajoutée.'),('Régénération','Guérison accélérée de blessures ordinaires selon leur gravité et son état. Ne soigne pas autrui, n’annule pas toutes les malédictions et ne permet pas de ressusciter.'),('Contrainte mentale','Influence limitée sur un humain non protégé, par contact visuel et avec l’accord du joueur concerné. La verveine protège la cible. Aucun contrôle des vampires, lecture des pensées ou pouvoir sur les rêves inclus.')]
 return p('Quatre capacités maximum à la création, actives et passives comprises. Les capacités manquantes et les améliorations se débloquent ensuite en jeu par achat en Arcana Flouz et validation du staff. Son ancienneté et les exploits de la série ne donnent aucun don supplémentaire.')+''.join('<div data-base-power="1"><h3 style="color:#f5d76e;font-size:1rem;">'+escape(a)+'</h3>'+p(b)+'</div>' for a,b in parts)+p('La faim, le soleil sans protection validée, la verveine et les autres vulnérabilités vampiriques restent à prendre en compte. Aucun objet magique ni immunité supplémentaire n’est accordé automatiquement.')
'''+source[end:]
source=source.replace('II. Nature et capacités','II. Quatre capacités de départ')
source=source.replace('Continuité Nexus Arcana : Klaus et Elijah sont vivants ; Finn et Esther sont revenus grâce à la Convergence. Ces retours ne constituent pas des pouvoirs reproductibles. Hope est pleinement tribride. Les proches conservent leur libre choix : le nom Mikaelson ne crée ni obéissance ni pardon automatique. Les métiers proposés et les détails des relations se personnalisent avec les joueurs concernés.','Continuité Nexus Arcana : Marcel est vampire et commence avec les quatre capacités indiquées. Son statut de vampire amélioré n’est pas acquis. Les dons manquants et les évolutions passent par la boutique en Arcana Flouz. Sa situation avec Rebekah, ses activités et sa place dans les communautés se construisent avec les joueurs concernés.')
# Keep the current universal creation notice if it has been added to the template.
source=source.replace("old=post.content\n", "old=post.content\n  notice_match=re.search(r'<section[^>]*data-creation-cap=\"4\"[^>]*>.*?</section>',old,re.S)\n")
source=source.replace("check=CheckHTML();check.feed(content);assert not check.stack", "content+=(notice_match.group(0) if notice_match else '')\n  check=CheckHTML();check.feed(content);assert not check.stack\n  assert content.count('data-base-power=\"1\"')==4")
exec(compile(source,'marcel-renderer','exec'))
