import json
import re
from html import escape
from pathlib import Path
from django.conf import settings
from django.db import transaction
from django.utils import timezone
from apps.forum.models import Topic

from scenario_layout_helpers import CheckHTML, p, section

VAMPIRE_POWERS=[
('Force vampirique','Force supérieure à celle d’une humaine, limitée à une action ciblée. Elle ne permet ni victoire automatique ni destruction massive. Les blessures, la faim et la fatigue influencent son efficacité.'),
('Vitesse vampirique','Accélération brève sur une courte distance dégagée. Ce n’est pas une téléportation : les obstacles comptent et une cible garde la possibilité de réagir.'),
('Régénération vampirique','Récupération accélérée de blessures ordinaires, selon leur gravité et l’alimentation. Elle ne neutralise pas toutes les malédictions, ne fait pas repousser librement un membre et ne permet pas de revenir après une destruction définitive.'),
('Contrainte mentale limitée','Suggestion simple à une personne humaine réceptive, avec contact visuel et accord du joueur concerné. La verveine et les protections adaptées empêchent l’effet. Aucun contrôle libre des vampires, effacement complet d’une identité ou consentement amoureux imposé.')]

DATA=[
dict(slug='elena-gilbert-salvatore',name='Elena Gilbert Salvatore',race='Vampire · double Petrova',camp='Bien',age='Apparence de jeune adulte depuis sa transformation · âge chronologique à harmoniser avec le forum',origin='Mystic Falls',job='Médecin · spécialité et lieu d’exercice à personnaliser',family='Épouse de Damon Salvatore · sœur de Jeremy Gilbert',quote='Je veux rester quelqu’un qui soigne, même lorsque ma nature me pousse à blesser.',
character=['Qualités : compatissante, courageuse, loyale, attentive, persévérante et capable de défendre ses proches avec détermination.', 'Défauts : culpabilise facilement, veut parfois sauver tout le monde, se montre obstinée et peut prendre des décisions à la place des autres sous prétexte de les protéger.', 'Elena n’est pas seulement douce. Lorsqu’elle pense qu’une personne est en danger, elle peut devenir très ferme et dépasser les limites qu’elle conseillait elle-même de respecter. Elle cherche à comprendre avant de condamner, mais les blessures répétées ont rendu sa confiance moins immédiate.', 'Sa nature vampirique rend le soin et la proximité humaine plus complexes. Elle ne prétend pas que la compassion suffit à maîtriser la faim. Elle se construit des repères, accepte le besoin de soutien et cherche une existence qui ne se résume ni à son couple ni aux menaces attachées à son visage.'],
history=[
('La jeune fille de Mystic Falls','Élevée par Grayson et Miranda Gilbert aux côtés de Jeremy, Elena connaît une vie familiale que l’accident du Wickery Bridge brise brutalement. Survivre alors que ses parents meurent la laisse avec un deuil et une culpabilité durables. L’écriture l’aide à mettre des mots sur ce qu’elle n’arrive pas toujours à dire. Elle tente de retrouver une place parmi ses amis sans comprendre encore les secrets qui entourent sa naissance.'),
('Un visage qui appartient à plusieurs histoires','Sa rencontre avec Stefan puis Damon Salvatore l’entraîne dans le monde surnaturel. Elena découvre sa ressemblance avec Katherine Pierce et la portée du sang des doubles. Elle apprend aussi la vérité sur ses parents biologiques, John Gilbert et Isobel Flemming. Ces révélations ne remplacent pas l’amour des Gilbert qui l’ont élevée. Elles lui montrent surtout combien d’autres personnes voudraient décider de son destin à partir de ses origines.'),
('Devenir vampire','Elena devient vampire malgré son désir initial de rester humaine. Elle doit composer avec une faim nouvelle, des émotions intenses et la peur de ne plus se reconnaître. Ses erreurs et les moments où elle s’éloigne de ses valeurs font partie de son histoire. Elle apprend que retrouver son humanité morale ne signifie pas effacer ce qu’elle a fait, mais choisir comment agir ensuite.'),
('La vie choisie avec Damon','Dans la continuité Nexus Arcana, Elena et Damon sont mariés, conformément au nom de son scénario. Elena demeure vampire : son avenir ne reprend donc pas à l’identique la vie humaine montrée à la fin de la série. Elle conserve un passé amoureux avec Stefan sans que celui-ci impose un triangle actuel. Les détails intimes de son mariage, les éventuels enfants et les étapes intermédiaires restent à convenir avec les joueurs concernés.'),
('Soigner dans un monde dangereux','Elena poursuit une vocation médicale. Sa pratique lui demande rigueur, apprentissage et maîtrise de sa faim ; elle n’utilise pas son sang comme une solution automatique. Le soin lui donne une place active dans la communauté et des rencontres en dehors des conflits familiaux. Elle veut pouvoir aider sans devenir le sacrifice que l’on attend dès qu’une magie exige le sang d’un double.'),
('La Convergence et les autres visages','Mystic Falls est désormais reliée aux autres villes du Nexus par des trajets ordinaires. Elena peut y travailler, se déplacer et rencontrer de nouvelles traditions surnaturelles. La présence de Katherine reste une source de méfiance, tandis que le retour de Tatia lui donne la possibilité de connaître une femme longtemps réduite à une histoire ancienne. Leur ressemblance ne crée ni intimité immédiate ni accord naturel : chacune doit pouvoir exister pour elle-même.')],
links=[('damon-salvatore','Damon Salvatore — Époux','Nous avons choisi une vie ensemble, avec ce que notre passé contient de beau et de difficile. Je veux que notre mariage repose sur la confiance et sur la possibilité de nous dire non. Nos habitudes, nos projets et les détails de notre vie commune sont à construire avec ton joueur.'),('stefan-salvatore','Stefan Salvatore — Ancien amour, lien durable','Tu as compté dans ma découverte du monde surnaturel et dans ma vie. Notre histoire mérite d’être reconnue sans nous obliger à la recommencer. La forme actuelle de notre amitié se définit ensemble, dans le respect de nos choix présents.'),('katherine-pierce','Katherine Pierce — Même visage, confiance brisée','Je connais le prix de tes mensonges et je ne peux pas te traiter comme une inconnue. Nous portons le même visage, mais tu ne peux pas décider de qui je suis. Une coopération reste possible face à une menace commune, sans effacer ce qui nous oppose.'),('tatia-petrova','Tatia Petrova — Une rencontre au-delà du double','J’aimerais te rencontrer comme une personne, pas comme une explication de mon existence. Je peux t’aider à comprendre ce monde si tu le souhaites. Notre ressemblance ne m’autorise pas à raconter ton histoire à ta place.')]),
dict(slug='katherine-pierce',name='Katherine Pierce',race='Vampire · double Petrova',camp='Neutre · intérêts personnels prioritaires',age='Apparence de jeune adulte · née au XVe siècle',origin='Bulgarie · identité de naissance : Katerina Petrova',job='Intermédiaire et négociatrice indépendante · couverture proposée',family='Mère de Nadia Petrova · vie sentimentale au choix',quote='J’ai passé des siècles à fuir. Je compte bien choisir où je reste.',
character=['Qualités : ingénieuse, observatrice, endurante, audacieuse, adaptable et redoutablement déterminée.', 'Défauts : manipulatrice, méfiante, orgueilleuse, possessive et prête à faire passer sa survie avant les conséquences pour les autres.', 'Katherine soigne son apparence et son assurance parce qu’elles lui permettent de garder l’initiative. Elle observe les désirs et les peurs, puis choisit ce qu’elle révèle. Son humour et son charme peuvent séduire, mais ils ne remplacent jamais une confiance qu’elle a rarement appris à offrir.', 'Sa peur de redevenir une victime explique ses réflexes sans les excuser. Derrière l’ironie demeurent des attachements, notamment celui à Nadia, qu’elle protège parfois en les niant. Elle peut choisir une alliance sincère, mais devra alors accepter de perdre un peu du contrôle auquel elle tient.'],
history=[
('Katerina avant Katherine','Née en Bulgarie au XVe siècle, Katerina Petrova donne naissance à Nadia, qui lui est retirée. Le rejet familial et la séparation la poussent vers l’exil. Cette première perte demeure une blessure derrière les noms et les vies qu’elle adoptera ensuite. Elle n’a pas toujours été la femme qui traite chaque rencontre comme une négociation.'),
('Échapper au sacrifice','En Angleterre, elle rencontre les Mikaelson et découvre que son sang de double intéresse Klaus pour un rituel qui lui coûterait la vie. Elle devient vampire pour lui échapper. Cette décision lui permet de survivre, mais la vengeance de Klaus frappe sa famille. Katherine apprend alors à changer de lieu, d’identité et d’alliés avant qu’un ennemi puisse refermer son piège.'),
('Les frères Salvatore','À Mystic Falls, en 1864, elle entre dans la vie de Stefan et Damon. Attirance, mensonges et contrôle se mêlent dans ces relations dont les conséquences traversent les décennies. Katherine tient à certaines personnes sans renoncer à les utiliser. La séparation et les retrouvailles futures ne lui donnent aucun droit sur les sentiments actuels des deux frères.'),
('Le retour d’un double','Découvrir Elena, puis revenir dans son entourage, fait renaître sa peur d’être remplacée autant que son envie de reprendre l’avantage. Katherine voit des occasions là où Elena voit des liens à protéger. Leur opposition devient personnelle, même lorsqu’elles affrontent les mêmes dangers. L’histoire de Nadia demeure également essentielle : la place actuelle de sa fille et leurs retrouvailles éventuelles sont à préciser avec le staff, sans inventer ici une présence déjà acquise.'),
('Une continuité propre au Nexus','Pour cette version, Katherine reste vampire. La guérison de son vampirisme, la possession d’Elena et le destin final de reine des Enfers ne sont pas retenus comme étapes imposées de cette continuité. Elle ne dispose donc ni de magie de Voyageuse active en supplément ni d’une autorité infernale. Son passé de fugitive et ses relations complexes constituent son point de départ ; aucun pouvoir exceptionnel ne vient récompenser son ancienneté.'),
('Rester sans se rendre','La Convergence ouvre des routes nouvelles et multiplie les interlocuteurs. Katherine pourrait vendre une information, négocier un refuge ou chercher qui convoite encore le sang des doubles. Sa présence parmi Elena et Tatia ne crée pas une famille unie par décret. Elle devra choisir si elle continue de traiter chaque relation comme une sortie de secours ou accepte, parfois, de tenir parole sans bénéfice immédiat.')],
links=[('elena-gilbert-salvatore','Elena Gilbert Salvatore — Rivale et miroir','Tu as eu des attaches que j’ai appris à perdre ou à sacrifier. Je peux mépriser ta confiance et envier ce qu’elle te permet de construire. Nous ne sommes pas interchangeables. Une entente ponctuelle ne suffit pas à effacer notre passé.'),('stefan-salvatore','Stefan Salvatore — Attachement ancien','Tu fais partie des rares personnes capables de me ramener à des sentiments que je préférerais maîtriser. Notre passé existe, mais je ne peux pas exiger qu’il détermine tes choix présents. Une reprise de relation n’est pas acquise.'),('damon-salvatore','Damon Salvatore — Une histoire de blessures','Je sais que mes choix t’ont marqué. Ton mariage avec Elena ne fait pas de notre passé une page blanche, mais il ne me donne pas davantage de place dans ta vie. Nous pouvons nous affronter ou négocier sans prétendre que la confiance est revenue.'),('tatia-petrova','Tatia Petrova — Celle qui nous a précédées','Tu portes ce visage sans avoir vécu mes siècles de fuite. Je pourrais chercher en toi des réponses ou une alliée, mais tu ne me dois rien. Ta vulnérabilité humaine peut éveiller chez moi de la prudence autant que la tentation de garder l’avantage.')]),
dict(slug='tatia-petrova',name='Tatia Petrova',race='Humaine · double Petrova revenue grâce au Nexus',camp='Bien',age='Âge physique de sa mort, jeune adulte · plus d’un millénaire sépare ses deux vies',origin='Ancien village des Mikaelson · monde contemporain à découvrir',job='Activité au choix · savoir-faire artisanal à développer',family='Veuve dans sa première vie · mère d’un enfant de cette époque',quote='Je ne suis pas le souvenir que vous avez gardé. Je suis celle qui doit vivre après.',
character=['Qualités : chaleureuse, indépendante, courageuse, attentive, persévérante et attachée aux liens qu’elle choisit.', 'Défauts : se referme lorsqu’elle se sent utilisée, supporte mal les décisions prises à sa place, masque parfois sa peur et peine à demander de l’aide dans un monde qu’elle ne connaît pas.', 'Tatia n’est ni une sainte ni une énigme destinée à réconcilier les Mikaelson. Elle a aimé, perdu, élevé un enfant et choisi sa vie avant que son sang ne devienne un enjeu magique. Son regard sur les autres mêle la tendresse à une volonté très nette de rester libre.', 'Revenir parmi des inconnus qui connaissent déjà son visage peut l’épuiser. Elle peut apprendre vite sans comprendre immédiatement les usages, les outils ou les conflits contemporains. Sa force se mesure aussi à sa capacité de dire qu’elle ne sait pas et de choisir à qui poser ses questions.'],
history=[
('Une femme avant la légende','Tatia vit dans le village où grandissent les Mikaelson, bien avant que leurs noms ne désignent une famille de vampires originels. Devenue veuve et mère, elle refuse que le deuil soit la seule définition de son avenir. Elijah et Niklaus éprouvent des sentiments pour elle, mais ses choix lui appartiennent. Son existence ne commence pas avec leur rivalité.'),
('Le sang du double','Son sang entre dans les rituels d’Esther et se trouve associé à la transformation des Mikaelson. Tatia ne maîtrise pas les conséquences de cette magie. Être un double ne fait pas d’elle une sorcière et ne signifie pas qu’elle accepte de devenir une ressource pour ceux qui recherchent la puissance.'),
('La mort derrière les récits','Elijah, récemment devenu vampire, perd le contrôle et la tue. Le rôle d’Esther dans les événements et les souvenirs enfouis d’Elijah contribuent ensuite à brouiller le récit de sa disparition. Tatia n’a pas suivi depuis l’au-delà tout ce que les vivants ont raconté à son sujet. Elle conserve des fragments de sa dernière rencontre et devra décider ce qu’elle souhaite apprendre.'),
('Le retour de la Convergence','Dans cette adaptation originale de Nexus Arcana, la Convergence réactive une ancienne trace magique liée à son sang et la ramène parmi les vivants. Elle retrouve un corps humain à l’âge de sa mort. Ce retour exceptionnel n’est ni un don personnel ni un procédé reproductible : Tatia ne peut pas ressusciter à volonté, ouvrir des passages vers les morts ou ramener son enfant avec elle.'),
('Le temps perdu','Elle découvre que plus d’un millénaire s’est écoulé. Son enfant, son foyer et la communauté de sa première vie appartiennent à une histoire dont elle devra retrouver les traces, sans promesse de réponses complètes. La rencontre avec les Mikaelson peut être désirée, redoutée ou repoussée. Leur regret ne lui impose ni pardon ni retour amoureux.'),
('Trois femmes, un même visage','Elena et Katherine lui ressemblent, mais ont chacune leurs souvenirs, leurs attachements et leurs blessures. Tatia peut apprendre auprès d’elles sans devenir leur protégée permanente. Elle conserve Petrova comme nom d’usage dans la continuité du forum. Dans les villes désormais voisines du Nexus, elle cherche un lieu où vivre, des repères et une activité qui lui appartiennent. Un premier déplacement, une archive retrouvée ou une conversation sur ses origines peuvent lancer ses sujets.')],
links=[('elena-gilbert-salvatore','Elena Gilbert Salvatore — Une aide possible','Tu connais les usages de ce monde et tu portes mon visage sans avoir mon histoire. Je peux accepter ton aide si elle me laisse la place d’apprendre et de choisir. J’aimerais découvrir qui tu es avant de parler de ce que notre sang représente.'),('katherine-pierce','Katherine Pierce — Un autre chemin de survie','Je sens que tu as appris à te défendre en ne donnant pas facilement ta confiance. Je ne connais pas encore toutes tes raisons. Notre ressemblance ne fait pas de moi ton alliée ni ton ennemie : ce sont nos actes qui décideront de notre lien.'),('elijah-mikaelson','Elijah Mikaelson — Amour ancien, blessure présente','Je garde le souvenir de l’homme que j’ai aimé et celui, brisé, de notre dernière rencontre. Je veux pouvoir chercher la vérité sans devoir te rassurer sur ta culpabilité. Ton pardon envers toi-même et le mien ne sont pas la même chose ; aucune réconciliation n’est imposée.'),('klaus-mikaelson','Niklaus Mikaelson — Un passé devenu lointain','Je t’ai connu avant les siècles et les récits qui entourent désormais ton nom. Je dois découvrir qui tu es devenu, et tu dois me laisser être autre chose qu’une femme de ton passé. Notre relation actuelle reste à construire.')]),
]

with transaction.atomic():
    wanted={d['slug'] for d in DATA}|{x[0] for d in DATA for x in d['links']}
    topics={t.slug:t for t in Topic.objects.select_for_update().filter(slug__in=wanted,category__slug='scenarios-a-prendre')}
    posts={slug:t.posts.select_for_update().order_by('created_at','pk').first() for slug,t in topics.items()}
    images={}
    for slug,post in posts.items():
        if post:
            m=re.search(r'<img\b[^>]*src=[\"\x27]([^\"\x27]+)',post.content)
            if m: images[slug]=m.group(1)
    backup=[]
    for d in DATA:
        t,post=topics[d['slug']],posts[d['slug']]
        assert post and 'Nom du pouvoir' in post.content and not t.scenario_link_cards,'Scénario déjà modifié'
        backup.append(dict(topic_id=t.pk,post_id=post.pk,content=post.content,scenario_link_cards=t.scenario_link_cards))
    folder=Path(settings.BASE_DIR)/'data/scenario_backups'; folder.mkdir(parents=True,exist_ok=True)
    (folder/('petrova-'+timezone.now().strftime('%Y%m%dT%H%M%S%f')+'.json')).write_text(json.dumps(backup,ensure_ascii=False),encoding='utf-8')
    for d in DATA:
        t,post=topics[d['slug']],posts[d['slug']]
        caption=re.search(r'<p\b[^>]*>([^<]*\bFt [^<]*)</p>',post.content,re.I)
        credit=re.search(r'<p class="scenario-credit-line"[^>]*>.*?(?:</p>|$)',post.content,re.S)
        assert caption and credit
        credit_html=credit.group(0).rstrip()
        if not credit_html.endswith('</p>'):
            credit_html+='</p>'
        content='<div data-petrova-scenario="1" style="font-family:Georgia,serif;background:#0d0a1a;color:#e2d9f3;padding:clamp(1rem,4vw,2rem);border-radius:10px;max-width:800px;margin:auto;"><p style="text-align:center;color:#a78bfa;font-size:.75rem;letter-spacing:.12em;">✦ Nexus Arcana · Livre des Ombres ✦</p><div style="display:flex;flex-wrap:wrap;align-items:center;gap:1.5rem;"><div style="flex:1;min-width:180px;"><h1 style="color:#f5d76e;font-size:2rem;">'+escape(d['name'])+'</h1>'+p(d['race']+' · '+d['camp'])+p('« '+d['quote']+' »')+'</div><figure style="margin:0;max-width:100%;"><img src="'+escape(images[d['slug']],quote=True)+'" alt="'+escape(d['name'])+'" style="width:200px;max-width:100%;height:320px;object-fit:cover;border-radius:8px;"><figcaption style="max-width:200px;font-size:.75rem;line-height:1.6;margin-top:.5rem;">'+caption.group(1).strip()+'</figcaption></figure></div>'
        fields=[('Âge',d['age']),('Origines',d['origin']),('Sexe','Féminin'),('Orientation sexuelle','Au choix du joueur'),('Famille et situation',d['family']),('Nature',d['race']),('Camp',d['camp']),('Métier',d['job'])]
        content+=section('I. Identité','<dl style="margin:0;">'+''.join('<dt style="color:#a78bfa;font-size:.8rem;margin-top:.65rem;">'+escape(k)+'</dt><dd style="margin:.15rem 0 0;">'+escape(v)+'</dd>' for k,v in fields)+'</dl>')
        if d['slug']=='tatia-petrova':
            content+=section('II. Nature humaine et aptitudes',p('Tatia ne possède aucun pouvoir actif surnaturel. Son statut de double et son retour exceptionnel ne lui accordent ni sorcellerie ni immunité. Les quatre aptitudes ci-dessous sont des savoir-faire humains proposés, pas quatre dons magiques.')+''.join(p(x) for x in ['Observation — Remarque des détails et les confronte à ce qu’elle connaît, sans détecter magiquement les mensonges.','Savoir-faire domestiques et artisanaux — Compétences de sa première vie, à préciser ; les outils modernes demandent un apprentissage.','Connaissance de son époque — Témoignage limité à ce qu’elle a réellement vécu, pas une mémoire universelle de l’histoire.','Adaptation et endurance — Persévérance humaine dans les tâches quotidiennes, sans résistance surnaturelle aux blessures.']))
        else:
            content+=section('II. Quatre pouvoirs de base',''.join('<div data-base-power="1"><h3 style="color:#f5d76e;font-size:1rem;">'+escape(name)+'</h3>'+p(text)+'</div>' for name,text in VAMPIRE_POWERS)+p('La faim de sang et les vulnérabilités vampiriques restent présentes. Le soleil exige une protection enchantée validée et l’entrée dans une habitation protégée nécessite une invitation. Aucun objet protecteur n’est accordé automatiquement. Les sens exceptionnels ou autres capacités non décrites ne s’ajoutent pas librement à ces quatre dons.'))
        content+=section('III. Âme et caractère',''.join(map(p,d['character'])))
        content+=section('IV. Mémoire des âges · Histoire',''.join('<h3 style="color:#f5d76e;font-size:1rem;">'+escape(name)+'</h3>'+p(text) for name,text in d['history']))
        content+=section('V. Repères pour le jeu',p('Adaptation Nexus Arcana : Elena et Katherine sont vampires ; Tatia est humaine, revenue grâce au Nexus. Les ressemblances ne permettent pas de contrôler une autre personne, de lire ses souvenirs ou de garantir une usurpation réussie. Les relations présentes et les révélations d’intrigue se construisent avec les joueurs concernés.'))+credit_html+'</div>'
        check=CheckHTML(); check.feed(content); assert not check.stack
        assert 'Montana' not in content and 'Évolution 1' not in content
        cards=[dict(title=title,text=text,gif=images.get(slug,'')) for slug,title,text in d['links']]
        post.content=content; post.save(update_fields=['content','is_edited','updated_at'])
        t.scenario_link_cards=cards; t.save(update_fields=['scenario_link_cards'])
        post.refresh_from_db(); t.refresh_from_db(); assert post.content==content and t.scenario_link_cards==cards
        print(d['name']+' : fiche et quatre liens enregistrés ; nature et balisage vérifiés.')
