from pathlib import Path
source=Path('fill_mikaelson_scenarios.py').read_text(encoding='utf-8-sig')
source=source.replace('mikaelson_data.json','hayley_data.json').replace('assert len(topics)==8','assert len(topics)==1').replace("'mikaelson-'","'hayley-'").replace('data-mikaelson-scenario','data-hayley-scenario')
source=source.replace('def verify(name):',"GIFS['Tyler Lockwood']='https://media1.tenor.com/m/zVCfiQi04eAAAAAC/tyler-lockwood-the-vampire-diaries-season-3.gif'\ndef verify(name):")
start=source.index('def abilities(d):');end=source.index('with transaction.atomic():',start)
source=source[:start]+'''def abilities(d):
 parts=[
 ('Capacités physiques et sens','Force, vitesse, agilité, réflexes et endurance surnaturels ; ouïe, odorat et vision accrus permettant notamment le pistage. La fatigue, la faim et l’état de l’adversaire comptent : aucune action n’est automatiquement réussie.'),
 ('Régénération et longévité','Guérison accélérée de nombreuses blessures et arrêt du vieillissement naturel. Elle reste vulnérable à la magie et aux blessures destructrices ; son hybridité ne constitue pas une invulnérabilité.'),
 ('Transformation et instincts lupins','Transformation complète ou partielle, crocs, instincts de chasse et morsure venimeuse dangereuse pour les vampires. Elle choisit ses transformations sans obligation de pleine lune. La colère peut renforcer ses réactions tout en altérant son jugement.'),
 ('Contrainte et rêves','Peut influencer un humain non protégé, modifier ses souvenirs par contact visuel et intervenir dans les rêves selon les capacités vampiriques. La verveine protège de la contrainte. Les effets sur un personnage joué nécessitent l’accord de son joueur.'),
 ('Sang vampirique et émotions','Son sang peut soigner des blessures humaines et permettre une transition si la personne meurt avec ce sang dans son organisme. Ses émotions sont amplifiées et elle possède la faculté vampirique de couper son humanité. Ces intrigues se construisent avec les personnes concernées.'),
 ('Particularités de l’hybride','Vit au soleil sans bague de jour et résiste au venin lupin ordinaire. Elle possède les capacités de ses deux natures, sans plafond de quatre pour cet héritage. Son statut ne lui donne ni sorcellerie, ni sang antidote comparable à celui de Klaus, ni création libre d’hybrides.'),
 ('Limites et vie de meute','La faim de sang, l’invitation dans une habitation protégée, la verveine, l’aconit et la magie restent à prendre en compte. La décapitation ou l’arrachement du cœur peuvent la tuer. Son rôle parmi les loups repose sur leurs liens et leur reconnaissance, pas sur un contrôle magique des autres personnages.')]
 return ''.join('<h3 style="color:#f5d76e;font-size:1rem;">'+escape(a)+'</h3>'+p(b) for a,b in parts)
'''+source[end:]
source=source.replace('Continuité Nexus Arcana : Klaus et Elijah sont vivants ; Finn et Esther sont revenus grâce à la Convergence. Ces retours ne constituent pas des pouvoirs reproductibles. Hope est pleinement tribride. Les proches conservent leur libre choix : le nom Mikaelson ne crée ni obéissance ni pardon automatique. Les métiers proposés et les détails des relations se personnalisent avec les joueurs concernés.','Continuité Nexus Arcana : Hayley est vivante et hybride, Hope pleinement tribride, Klaus et Elijah présents. La mort finale de Hayley n’est pas retenue. Ses liens avec la meute, son activité et sa situation sentimentale actuelle se construisent avec les joueurs concernés. Les capacités naturelles sont décrites sans évolutions à acheter dans cette fiche.')
exec(compile(source,'hayley-renderer','exec'))
