import json
import re
from html import escape
from pathlib import Path
from django.conf import settings
from django.db import transaction
from django.utils import timezone
from apps.forum.models import Topic

# Reuse only rendering helpers; do not execute the Montana data or mutations.
from scenario_layout_helpers import CheckHTML, p, section

DATA = [
dict(slug='billie-jenkins', name='Billie Jenkins', age='Adulte, désormais plus âgée physiquement que Christy · âge exact à fixer selon la chronologie du forum', quote='Je peux te tendre la main sans te laisser choisir à ma place.', camp='Bien', job='Formatrice en autodéfense · activité proposée',
powers=[('Télékinésie', 'Déplace un petit objet visible ou produit une poussée brève à courte portée. L’effort dépend de la masse et de la précision. Une attaque dirigée contre un personnage lui laisse la possibilité de réagir ; aucun contrôle des organes.'), ('Projection limitée', 'Adaptation équilibrée pour Nexus Arcana : par concentration, modifie brièvement une propriété simple d’un petit objet inerte, comme sa couleur ou sa forme superficielle. Pas de création de vie, de résurrection, de voyage temporel ni de réécriture libre de la réalité. Le rituel ayant ramené Christy est un événement exceptionnel du contexte, pas un usage reproductible de ce don.'), ('Troisième pouvoir — Au choix', 'À choisir dans le grimoire, en cohérence avec sa nature de sorcière et après validation du staff.'), ('Quatrième pouvoir — Au choix', 'À choisir dans le grimoire avec des limites propres ; l’expérience passée ne donne pas de capacité supplémentaire.')],
character=['Qualités : courageuse, inventive, déterminée, loyale, directe et capable de remettre ses certitudes en question.', 'Défauts : impulsive, obstinée, portée à agir seule, exigeante envers elle-même et vulnérable lorsqu’il s’agit de sa sœur.', 'Billie conserve un esprit vif et un humour parfois mordant. Elle préfère essayer une solution plutôt que rester longtemps à discuter de ce qui pourrait mal tourner. Les années lui ont appris à préparer ses gestes, sans lui enlever le réflexe de s’interposer lorsqu’une personne est menacée.', 'La culpabilité qu’elle porte envers Christy ne lui fait plus confondre affection et obéissance. Elle veut retrouver sa sœur, mais ne consentira pas à sacrifier d’autres personnes pour apaiser leur passé. Poser cette limite est difficile, surtout lorsqu’elle craint que Christy y voie une nouvelle trahison.'],
history=[
('Une absence au cœur de l’enfance', 'L’enlèvement de Christy laisse dans la vie de Billie une question qui ne cesse de revenir : pourquoi sa sœur a-t-elle disparu et comment la retrouver ? Elle grandit avec des souvenirs incomplets et une détermination qui prend peu à peu toute la place. Lorsqu’elle découvre ses propres dons, le surnaturel devient à la fois un danger concret et une piste possible vers cette absence familiale.'),
('Les Halliwell', 'Sa rencontre avec les Halliwell lui offre un cadre pour apprendre. Billie se montre volontaire, parfois trop sûre de pouvoir tout affronter seule. Auprès de Paige, Piper et Phoebe, elle découvre que pratiquer la magie signifie aussi répondre de ses décisions. Elle s’attache à elles, mais son désir de retrouver Christy demeure un point fragile que leurs ennemis savent exploiter.'),
('Retrouver puis perdre', 'Les retrouvailles avec Christy ne lui rendent pas simplement la sœur qu’elle imaginait. Des années d’endoctrinement ont façonné les convictions de l’aînée. Billie se laisse entraîner contre les Halliwell avant de reconnaître la manipulation. Lors du dernier affrontement, Christy refuse sa main tendue et lance une boule de feu. Billie la renvoie pour se défendre ; Christy meurt. Ce geste reste une blessure, même lorsqu’elle sait qu’elle devait empêcher une nouvelle attaque.'),
('Continuer à vivre', 'Billie traverse les années suivantes sans effacer ce qui s’est passé. Dans cette continuité du forum, elle poursuit sa vie de sorcière et cherche à agir avec davantage de discernement. Ses activités, ses amitiés et ses éventuelles relations sentimentales restent à développer. Elle ne se réduit pas au deuil : elle a appris, travaillé et changé pendant que le visage de Christy demeurait figé dans ses souvenirs.'),
('Le réceptacle de la Triade', 'Au moment de la Convergence, des objets de leur enfance réagissent et des rêves la ramènent vers une présence familière. Ses recherches lui permettent de découvrir, dans cette adaptation Nexus Arcana, un réceptacle auquel la Triade avait lié l’âme de Christy afin de conserver son arme après sa mort. Privée de ses anciens maîtres, cette prison avait subsisté. Les perturbations du Nexus en fragilisent enfin les liens.'),
('Une libération devenue résurrection', 'Billie prépare un rituel pour libérer l’âme de sa sœur et lui permettre de trouver la paix. Elle ne cherche pas à fabriquer une seconde vie. L’énergie de la Convergence traverse pourtant le rituel et rend à Christy un corps vivant, à l’âge de sa mort. Le réceptacle se brise et perd sa fonction. Ce concours de circonstances est unique : Billie n’acquiert pas le pouvoir de ramener les défunts.'),
('Deux sœurs à réapprendre', 'À San Francisco, Billie se retrouve face à une sœur qui n’a pas vécu les mêmes années. Elle ressent du soulagement, de la tendresse et une peur qu’elle n’aime pas reconnaître. Elle propose un soutien, pas une confiance sans conditions. La découverte de la ville, une discussion interrompue ou une rencontre avec les Halliwell peuvent ouvrir leur jeu. Leur réconciliation devra se construire, et aucune des deux ne peut en décider seule.')],
links=[('christie-jenkins','Christy Jenkins — Sœur aînée revenue à la vie','Je voulais te libérer, et tu es revenue vivante. Je retrouve ton visage alors que j’ai changé pendant des années. Je veux te connaître au-delà de ce qu’ils ont fait de toi, mais je ne te suivrai plus contre ceux que je souhaite protéger. Nous avons le droit de nous aimer sans être d’accord.'), ('paige-matthews-charmed-one','Paige Matthews Mitchell — Ancienne guide','Tu as participé à mon apprentissage et tu connais aussi mes erreurs. Je souhaite pouvoir te parler du retour de Christy sans te demander de lui faire confiance immédiatement. Notre relation actuelle se construit avec ta joueuse, à partir de ce passé partagé.'), ('piper-halliwell-charmed-one','Piper Halliwell — Une confiance à préserver','Je comprends que tu penses d’abord à la sécurité de ta famille. Le retour de Christy ne doit pas te contraindre à oublier ce que nous avons traversé. Je veux te montrer que mes limites sont claires, même lorsque ma sœur est concernée.'), ('phoebe-halliwell-charmed-one','Phoebe Halliwell Turner — Un regard sur les secondes chances','Tu connais les liens qui résistent à des histoires difficiles. J’aimerais pouvoir parler avec toi sans attendre que tu choisisses pour moi. Ton soutien éventuel ne vaut pas pardon automatique pour Christy : cette place lui appartient à construire.')]),
dict(slug='christie-jenkins', name='Christy Jenkins', age='Apparence et âge physique de sa mort · les années écoulées depuis ne se lisent pas sur son visage', quote='Si cette vie m’appartient, je veux apprendre à la choisir.', camp='À choisir en jeu · aucune allégeance automatique à la Triade', job='Reconstruction d’une vie civile · activité au choix',
powers=[('Pyrokinésie', 'Produit une petite flamme à proximité et tente de la maintenir sous contrôle. Une émotion forte peut interrompre sa maîtrise. Aucun brasier de zone ni immunité générale au feu ; les attaques importantes de son passé ne sont pas accessibles automatiquement au départ.'), ('Télépathie limitée', 'Avec l’accord du joueur concerné, perçoit une pensée superficielle lors d’un contact bref et concentré. Pas de lecture complète des souvenirs, de vérité garantie, de contrôle mental ou d’accès permanent à l’esprit de Billie.'), ('Troisième pouvoir — Au choix', 'À choisir dans le grimoire selon sa nature de sorcière, avec validation du staff. Sa résurrection ne lui donne pas une nouvelle race.'), ('Quatrième pouvoir — Au choix', 'À définir avec des limites précises. Aucun don supplémentaire ne découle du réceptacle ou de son ancien lien avec la Triade.')],
character=['Qualités : tenace, observatrice, courageuse, attachée à sa sœur et capable d’une grande intensité dans ses engagements.', 'Défauts : méfiante, rigide dans ses convictions, prompte à se sentir trahie, impulsive sous la peur et peu habituée à remettre en question ceux qui lui ont donné des réponses.', 'Christy revient avec des réflexes de survie et des certitudes qui ont longtemps organisé son monde. Elle peut interpréter une précaution comme une menace ou une contradiction comme un rejet. Cela ne lui enlève ni son intelligence ni la responsabilité de ses choix, mais rend la confiance lente et parfois inconfortable.', 'Sous cette défense subsiste le désir de compter pour quelqu’un autrement que par ses pouvoirs. Retrouver Billie lui offre une possibilité, pas une guérison instantanée. Christy peut apprendre à reconnaître la manipulation, chercher une voie plus juste ou se refermer sur sa rancœur : son camp reste à construire en jeu.'],
history=[
('Une enfance interrompue', 'Christy est enlevée alors qu’elle est encore enfant et séparée de Billie. Ses ravisseurs lui retirent ses repères et façonnent progressivement son interprétation du monde. La Triade lui présente une mission comme une vérité et lui apprend à reconnaître des ennemies là où elle aurait pu rencontrer des alliées. Les souvenirs de sa première famille persistent, mais se mêlent à ce qu’on lui répète pendant des années.'),
('L’arme que l’on voulait créer', 'Sa puissance intéresse ceux qui la manipulent davantage que sa personne. Christy finit par défendre les convictions qui lui ont été inculquées, parce qu’elles donnent un sens à ce qu’elle a subi. Dans la version Nexus Arcana, la Triade prend également une précaution secrète : un lien entre son âme et un réceptacle doit empêcher la disparition définitive de son instrument. Christy ignore alors l’existence de cette prison.'),
('Billie retrouvée', 'Retrouver sa petite sœur réveille un attachement réel, mais Christy l’inscrit dans la mission qu’on lui a donnée. Elle entraîne Billie dans sa lutte contre les Halliwell. Lorsque Billie comprend la manipulation et refuse de poursuivre, Christy voit surtout une rupture insupportable. Elle ne parvient pas à entendre la main tendue derrière ce refus.'),
('La dernière flamme', 'Christy lance une boule de feu vers Billie et les Halliwell. Billie la renvoie en se défendant et Christy meurt. Son retour ne change ni cet affrontement ni la responsabilité de son attaque. Son âme demeure ensuite captive du réceptacle : elle en conserve des impressions obscures et discontinues, sans avoir observé les années suivantes ni appris les secrets des vivants.'),
('La fracture du Nexus', 'La Convergence affaiblit le réceptacle. Billie perçoit des signes et entreprend de libérer sa sœur pour lui permettre de trouver la paix. Au cours du rituel, l’énergie du Nexus provoque une résurrection inattendue. Christy retrouve un corps vivant, au même âge physique qu’à sa mort. Le réceptacle se brise ; aucun lien de possession ou ordre secret de la Triade n’est imposé à cette nouvelle vie.'),
('Un monde qui a continué sans elle', 'Billie est désormais plus âgée physiquement et possède une existence que Christy ne connaît pas. Les Halliwell, leurs proches et San Francisco ont eux aussi changé. Christy doit apprivoiser ce décalage tout en comprenant que la joie de son retour peut coexister avec la méfiance. Elle n’obtient ni pardon immédiat ni droit de reprendre la place qu’elle occupait auprès de sa sœur.'),
('Apprendre à choisir', 'Le scénario commence après son retour. Christy est vivante, sorcière, avec quatre pouvoirs de base et une histoire à reconstruire. Elle peut chercher les preuves de ce qu’on lui a caché, accepter une aide limitée ou refuser de parler de sa captivité. Une rencontre avec l’une des Halliwell, un souvenir d’enfance ou une sortie avec Billie suffisent à amorcer un sujet. Ce qui vient ensuite dépend de ses actes, sans retour forcé vers le Mal ni rédemption déjà accomplie.')],
links=[('billie-jenkins','Billie Jenkins — Petite sœur, point d’attache','Je te retrouve plus âgée que moi alors que je garde ton ancien visage dans mes souvenirs. Tu dis avoir voulu me libérer, et j’ignore encore comment recevoir ce geste après notre dernier affrontement. Je veux comprendre ce qu’il reste de nous. Ton affection ne signifie plus que tu me suivras partout.'), ('paige-matthews-charmed-one','Paige Matthews Mitchell — Une rencontre à reprendre','Je t’ai longtemps vue à travers les convictions que l’on m’avait imposées. Tu as aidé Billie à devenir la femme que je découvre aujourd’hui. Je peux chercher à te connaître autrement, mais ni ta confiance ni ton aide ne me sont dues.'), ('piper-halliwell-charmed-one','Piper Halliwell — Les conséquences du passé','Je sais que mon retour peut représenter un danger à tes yeux. Je peux me sentir rejetée par tes précautions, mais elles ne sont pas sans histoire. Notre premier échange devra laisser à chacune le droit de poser ses limites.'), ('phoebe-halliwell-charmed-one','Phoebe Halliwell Turner — Un dialogue possible','Tu fais partie de celles que j’ai voulu combattre. Un dialogue pourrait m’obliger à regarder ce que je croyais savoir sur vous. Je ne peux pas te demander de me pardonner avant même d’avoir compris et reconnu mes actes.')]),
]

with transaction.atomic():
    slugs = {d['slug'] for d in DATA} | {link[0] for d in DATA for link in d['links']}
    topics = {t.slug:t for t in Topic.objects.select_for_update().filter(slug__in=slugs, category__slug='scenarios-a-prendre')}
    assert set(topics) == slugs
    posts = {slug:t.posts.select_for_update().order_by('created_at','pk').first() for slug,t in topics.items()}
    images = {slug:re.search(r'<img\b[^>]*src=[\"\x27]([^\"\x27]+)',post.content).group(1) for slug,post in posts.items()}
    backup = []
    for d in DATA:
        t,post = topics[d['slug']],posts[d['slug']]
        assert 'Nom du pouvoir' in post.content and not t.scenario_link_cards, 'Scénario déjà modifié.'
        backup.append(dict(topic_id=t.pk,post_id=post.pk,content=post.content,scenario_link_cards=t.scenario_link_cards))
    folder = Path(settings.BASE_DIR)/'data/scenario_backups'
    folder.mkdir(parents=True,exist_ok=True)
    (folder/('jenkins-'+timezone.now().strftime('%Y%m%dT%H%M%S%f')+'.json')).write_text(json.dumps(backup,ensure_ascii=False),encoding='utf-8')
    for d in DATA:
        t,post = topics[d['slug']],posts[d['slug']]
        caption = re.search(r'<p\b[^>]*>([^<]*\bFt [^<]*)</p>',post.content,re.I)
        credit = re.search(r'<p class="scenario-credit-line"[^>]*>.*?</p>',post.content,re.S)
        assert caption and credit, 'Légende ou crédit manquant.'
        content = '<div data-jenkins-scenario="1" style="font-family:Georgia,serif;background:#0d0a1a;color:#e2d9f3;padding:clamp(1rem,4vw,2rem);border-radius:10px;max-width:800px;margin:auto;"><p style="text-align:center;color:#a78bfa;font-size:.75rem;letter-spacing:.12em;">✦ Nexus Arcana · Livre des Ombres ✦</p><div style="display:flex;flex-wrap:wrap;align-items:center;gap:1.5rem;"><div style="flex:1;min-width:180px;"><h1 style="color:#f5d76e;font-size:2rem;">'+escape(d['name'])+'</h1>'+p('Sorcière · '+d['camp'])+p('« '+d['quote']+' »')+'</div><figure style="margin:0;max-width:100%;"><img src="'+escape(images[d['slug']],quote=True)+'" alt="'+escape(d['name'])+'" style="width:200px;max-width:100%;height:320px;object-fit:cover;border-radius:8px;"><figcaption style="max-width:200px;font-size:.75rem;line-height:1.6;margin-top:.5rem;">'+caption.group(1).strip()+'</figcaption></figure></div>'
        identity = [('Âge',d['age']),('Date de naissance','À harmoniser avec la chronologie du forum'),('Sexe','Féminin'),('Orientation sexuelle','Au choix du joueur'),('Situation sentimentale','Au choix, sans relation imposée'),('Race','Sorcière'),('Camp',d['camp']),('Résidence','San Francisco'),('Métier',d['job'])]
        content += section('I. Identité','<dl style="margin:0;">'+''.join('<dt style="color:#a78bfa;font-size:.8rem;margin-top:.65rem;">'+escape(k)+'</dt><dd style="margin:.15rem 0 0;">'+escape(v)+'</dd>' for k,v in identity)+'</dl>')
        content += section('II. Pouvoirs de base',''.join('<div data-base-power="1"><h3 style="color:#f5d76e;font-size:1rem;">'+escape(name)+'</h3>'+p(text)+'</div>' for name,text in d['powers']))
        content += section('III. Âme et caractère',''.join(map(p,d['character'])))
        content += section('IV. Mémoire des âges · Histoire',''.join('<h3 style="color:#f5d76e;font-size:1rem;">'+escape(title)+'</h3>'+p(text) for title,text in d['history']))
        content += section('V. Repères pour le jeu',p('La captivité de l’âme, le réceptacle et la résurrection lors de la Convergence constituent une adaptation originale de Nexus Arcana. Le retour est déjà survenu au début du jeu ; sa datation précise se cale sur le contexte. Les deux sœurs gardent leurs souvenirs du dernier affrontement, avec leurs perceptions différentes.')+p('La résurrection n’accorde aucun pouvoir supplémentaire, aucune immortalité et aucune reconstitution automatique du Pouvoir Ultime. Les liens avec les Halliwell reprennent le passé commun ; leur état présent, la confiance et le pardon restent à construire avec leurs joueurs.'))
        content += credit.group(0)+'</div>'
        checker=CheckHTML(); checker.feed(content)
        assert not checker.stack and content.count('data-base-power="1"')==4
        assert 'Montana' not in content and 'Évolution 1' not in content
        cards=[dict(title=title,gif=images[slug],text=text) for slug,title,text in d['links']]
        post.content=content
        post.save(update_fields=['content','is_edited','updated_at'])
        t.scenario_link_cards=cards
        t.save(update_fields=['scenario_link_cards'])
        post.refresh_from_db(); t.refresh_from_db()
        assert post.content==content and t.scenario_link_cards==cards
        print(d['name']+' : fiche complète, quatre pouvoirs de base dont deux au choix, quatre liens. Balisage vérifié.')
