from pathlib import Path
source=Path('fill_mikaelson_scenarios.py').read_text(encoding='utf-8-sig')
source=source.replace('mikaelson_data.json','davina_data.json').replace('assert len(topics)==8','assert len(topics)==1').replace("'mikaelson-'","'davina-'").replace('data-mikaelson-scenario','data-davina-scenario')
source=source.replace('def verify(name):',"GIFS['Vincent Griffith']='https://media1.tenor.com/m/scAqhVKhcYcAAAAC/vincent-griffith-yusuf-gatewood.gif'\ndef verify(name):")
start=source.index('def abilities(d):');end=source.index('with transaction.atomic():',start)
source=source[:start]+'''def abilities(d):
 parts=[('Télékinésie','Déplace un petit objet visible à courte distance avec concentration. Le poids et la précision augmentent la fatigue ; aucun contrôle des organes ou du corps d’autrui.'),('Allumage magique','Allume une bougie ou une petite matière combustible proche. Ne contrôle pas un incendie, ne procure aucune immunité au feu et ne permet pas d’enflammer directement une personne.'),('Bouclier magique','Forme brièvement un écran qui amortit un impact limité. Peut céder ; ne renvoie pas les attaques et ne protège pas tout un bâtiment.'),('Perception des enchantements','Au contact d’un objet, ressent une magie active. Ne révèle pas automatiquement l’auteur, la formule ou les intentions ; ne permet pas à elle seule de dissiper l’effet.')]
 return p('Quatre capacités maximum à la création, actives et passives comprises. Les capacités manquantes et les améliorations se débloquent en jeu par achat en Arcana Flouz et validation du staff.')+''.join('<div data-base-power="1"><h3 style="color:#f5d76e;font-size:1rem;">'+escape(a)+'</h3>'+p(b)+'</div>' for a,b in parts)+p('Les connaissances des grimoires servent à étudier et préparer ; elles ne donnent pas tous les sorts. La puissance de la Moisson, les dons des Ancêtres et ses anciens exploits ne sont pas disponibles automatiquement. Les grands rituels suivent les règles du forum et ne contournent pas les capacités acquises. Davina demeure vulnérable aux blessures et à l’épuisement.')
'''+source[end:]
source=source.replace('II. Nature et capacités','II. Quatre capacités de départ')
source=source.replace('Continuité Nexus Arcana : Klaus et Elijah sont vivants ; Finn et Esther sont revenus grâce à la Convergence. Ces retours ne constituent pas des pouvoirs reproductibles. Hope est pleinement tribride. Les proches conservent leur libre choix : le nom Mikaelson ne crée ni obéissance ni pardon automatique. Les métiers proposés et les détails des relations se personnalisent avec les joueurs concernés.','Continuité Nexus Arcana : Davina est une sorcière vivante et commence avec les quatre capacités décrites. Les dons manquants et les évolutions passent par la boutique en Arcana Flouz. Sa relation avec Kol, ses études et sa place dans les covens se construisent avec les joueurs concernés. Aucun titre passé n’impose l’obéissance d’autrui.')
source=source.replace("old=post.content\n", "old=post.content\n  notice_match=re.search(r'<section[^>]*data-creation-cap=\"4\"[^>]*>.*?</section>',old,re.S)\n")
source=source.replace('check=CheckHTML();check.feed(content);assert not check.stack',"content+=(notice_match.group(0) if notice_match else '')\n  check=CheckHTML();check.feed(content);assert not check.stack\n  assert content.count('data-base-power=\"1\"')==4")
exec(compile(source,'davina-renderer','exec'))
