# Generated by Django 6.0.2 on 2026-02-28 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='age_personnage',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Âge du personnage'),
        ),
        migrations.AddField(
            model_name='user',
            name='avatar_name',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Avatar (célébrité)'),
        ),
        migrations.AddField(
            model_name='user',
            name='compte_bancaire',
            field=models.IntegerField(default=0, help_text='Montant en monnaie fictive, modifiable uniquement par un administrateur.', verbose_name='Compte bancaire RP'),
        ),
        migrations.AddField(
            model_name='user',
            name='double_compte',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Double compte'),
        ),
        migrations.AddField(
            model_name='user',
            name='groupe',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='lieu_residence',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Lieu de résidence'),
        ),
        migrations.AddField(
            model_name='user',
            name='pouvoirs',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='user',
            name='pseudo',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='race',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='sexe',
            field=models.CharField(blank=True, choices=[('feminin', 'Féminin'), ('masculin', 'Masculin'), ('indetermine', 'Indéterminé')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='situation',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Situation sociale et familiale'),
        ),
    ]
