# Generated by Django 6.0.2 on 2026-02-28 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='nature',
            field=models.CharField(blank=True, default='', help_text='Sous-catégorie de la race (ex : Furie, Succube, Fantôme...)', max_length=100, verbose_name='Nature'),
        ),
    ]
