# Generated by Django 5.2.11 on 2026-03-01 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_avatar_no_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('fondatrice', 'Fondatrice'), ('admin', 'Administrateur'), ('moderator', 'Modérateur'), ('user', 'Utilisateur')], default='user', max_length=20),
        ),
    ]
