# Generated by Django 5.2.11 on 2026-03-01 21:32

import apps.users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'Un personnage avec ce nom existe déjà.'}, max_length=150, unique=True, validators=[apps.users.models.RelaxedUsernameValidator()], verbose_name='Nom du personnage'),
        ),
    ]
