# Generated by Django 5.2.11 on 2026-09-14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_alter_user_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="signature",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Texte libre ou URL directe vers une image/GIF de signature.",
                verbose_name="Signature",
            ),
        ),
    ]
