# Generated by Django 5.1 on 2026-09-14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_user_signature"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="quartier_residentiel",
            field=models.CharField(blank=True, default="", max_length=150, verbose_name="Quartier résidentiel"),
        ),
        migrations.AddField(
            model_name="user",
            name="credits",
            field=models.TextField(blank=True, default="", help_text="Crédits pour les images, GIFs ou ressources du profil.", verbose_name="Crédits"),
        ),
    ]
