# Generated by Django 5.1 on 2026-09-14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forum", "0010_topic_scenario_link_cards"),
    ]

    operations = [
        migrations.AddField(
            model_name="topic",
            name="scenario_profile",
            field=models.JSONField(blank=True, default=dict, help_text="Informations structurées de la fiche d'un scénario."),
        ),
    ]
