# Generated by Django 5.1 on 2026-09-14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("forum", "0011_topic_scenario_profile"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="topic",
            name="scenario_profile",
        ),
    ]
